### ISSUE TITLE
Add `.web.js` and `.web.jsx` to resolve extension

### ISSUE THREAD

**Issue by piu130** [neutrinojs/neutrino#1056]
### Feature request or enhancement

We have some `react-native-web` support [here](https://github.com/neutrinojs/neutrino/blob/master/packages/react/index.js#L52) in the react-preset.
For multi-platform support react-native-web need `.web.js{x}` files to be loaded like `.android.js` and `.ios.js` files. See [here](https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md#multi-platform-applications).
We should add those extensions somewhere in a preset or middleware (`neutrino.config.resolve.extensions`).

**Comment by edmorley** [comment]
That makes sense - thank you for filing :-)

Presumably the `@neutrinojs/react` preset would need to:

```js
  neutrino.config
    .resolve
      .extensions
        .merge(['.web.js', '.web.jsx']);
```

(That is presuming the order of [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolve-extensions) doesn't matter?)

**Comment by piu130** [comment]
The order does matter:
```js
// sayHello/index.js
export default () => console.log('hello')
```
```js
// sayHello/index.web.js
export default () => console.log('hello web')
```
```js
// index.js
import sayHello from './sayHello'
sayHello()
```
`index.js` logs `hello` if the extensions are added and `hello web` if the extensions are prepended.
We should prepend the extensions. Does merge prepend?

**Comment by edmorley** [comment]
`.merge()` appends unfortunately:
https://github.com/neutrinojs/webpack-chain/blob/815bfd173a2dc6f802b66a48cdb2c4d2ff47df9f/src/ChainedSet.js#L37-L40

...so I guess with the current webpack-chain API we'd need multiple `.prepend()` calls:
https://github.com/neutrinojs/webpack-chain/blob/815bfd173a2dc6f802b66a48cdb2c4d2ff47df9f/src/ChainedSet.js#L14-L17

**Comment by piu130** [comment]
Created a [PR](https://github.com/neutrinojs/neutrino/pull/1064).
