### ISSUE TITLE
How do you adjust config in client side react code based on environment variables?

### ISSUE THREAD

**Issue by bingomanatee** [neutrinojs/neutrino#1102]
### Feature request or enhancement?

Please describe your request in detail. Use the following questions as guidance: 

- What is the goal of the change?
  I would like to know is there a way to combine NODE_ENV to get a particular .env file loaded into the React code for build? I.e., NODE_ENV=production yarn build pulls one set of variables (Ideally including process.env) and NODE_ENV=development pulls a separate config file for things like the API server. 

- What are the pros and cons of the change?
  Easier development for multi-environment builds.

- Could this dramatically improve the experience of our users?
  Maybe. It could definitely improve them. And I think its more of an understanding than a development thing.

**Comment by eliperelman** [comment]
In the past I have used the [dotenv](https://github.com/motdotla/dotenv) package. For an example with the neutrino build command:

```sh
neutrino build --require dotenv/config
```

You can then tell Neutrino to inject these environment variables in your neutrinorc:

```js
['@neutrinojs/env', [
  'NODE_ENV',
  'APPLICATION_NAME',
  'LOGIN_STRATEGIES',
  'TASKCLUSTER_ROOT_URL',
]],
```

Here is a project which does this:

https://github.com/taskcluster/taskcluster-web
https://github.com/taskcluster/taskcluster-web/blob/master/.neutrinorc.js
https://github.com/taskcluster/taskcluster-web/blob/master/package.json#L11-L12

Please re-open if this does not answer the question.
