### ISSUE TITLE
Set path to .neutrinorc.js

### ISSUE THREAD

**Issue by piu130** [neutrinojs/neutrino#1106]
### Feature request or enhancement?

Currently there is no way to pass the path to the `.neutrinorc.js` so you have to put it in the root folder. For `react-native(-web)` (and others) it would be nice to have the config in a folder called `web`, because android config is in `android` and ios config in `ios`.

Example:
`neutrino start --config web/.neutrinorc.js`
or maybe:
`neutrino start web/.neutrinorc.js`.

**Comment by eliperelman** [comment]
@piu130 for Neutrino v8, the `.neutrinorc.js` file is middleware, so you can use the `--use` flag to set where this is located:

```sh
neutrino start --use web/.neutrinorc.js
```

**Comment by piu130** [comment]
@eliperelman should we add this to the `customization.md`?
