### ISSUE TITLE
Leftover @neutrinojs/fork references in library preset docs

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1126]
The now-removed `@neutrinojs/fork` preset is still referenced here:
https://master.neutrinojs.org/packages/library/#generating-multiple-builds

We should convert to use the approach mentioned here:
https://master.neutrinojs.org/usage/#using-multiple-presets
(or else remove most of the section and just link to the usage page)

**Comment by eliperelman** [comment]
Fixed by #1127.
