### ISSUE TITLE
Decide whether we should enable devServer.overlay

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1131]
This seems like it might be a DX win (eg CRA has an overlay, albeit a custom one):
https://webpack.js.org/configuration/dev-server/#devserver-overlay

**Comment by timkelty** [comment]
Whoa I didn't even know about that! I'm a fan!

**Comment by edmorley** [comment]
So I think it would be good to enable this, but perhaps only for errors and not warnings (ie: we should use `overlay: true`, which does exactly that). This would mean a compile not completing due to an error would at least result in a message being shown in the page content, rather than the blank page etc.

The only question is what we should do with issues found by eslint-loader. ESLint itself has concepts of "errors" and "warnings", but many presets (such as AirBnb) set most rules to "error". I think it's a bit too noisy to surface all of these in the devserver overlay - for example when prototyping a quick change it seems unhelpful to block the entire page view to warn about incorrect indentation.

So perhaps enabling the overlay needs to be blocked on also setting `emitWarning: true` (which forces all issues to be treated as warnings) in `@neutrinojs/eslint` when in development?

**Comment by timkelty** [comment]
> So perhaps enabling the overlay needs to be blocked on also setting emitWarning: true (which forces all issues to be treated as warnings) in @neutrinojs/eslint when in development?

Seems reasonable to me!
