### ISSUE TITLE
Issue with importing  font.

### ISSUE THREAD

**Issue by pdoongarwal** [neutrinojs/neutrino#1134]
Trying to import Roboto font.
```
module.exports = {
  use: [
    ['@neutrinojs/airbnb', {
      eslint: {
        rules: {
          "jsx-a11y/anchor-is-valid": ["error", {
            "components": ["Link"],
            "specialLink": ["to"]
          }]
        }
      }
    }],
    [
      '@neutrinojs/react', {
        html: {
          title: 'Arya'
        },
        publicPath: '/',
        links: [{
          href: 'https://fonts.googleapis.com/css?family=Roboto',
          rel: 'stylesheet'
        }]
      }
    ],
    '@neutrinojs/karma',
    {
      devServer: {
        port: 3000
      }
    }
  ]
};
```
This does not work. What am I doing wrong?

_Originally posted by @pdoongarwal in https://github.com/neutrinojs/neutrino/issue_comments#issuecomment-423646093_

**Comment by edmorley** [comment]
Hi! Presuming this is with Neutrino 8, the `links` settings need to go under `html` rather than being a top-level option of `@neutrinojs/react`. 

See:
https://neutrinojs.org/packages/web/#preset-options

**Comment by pdoongarwal** [comment]
Thanks. It works. Although, I was not able to find it in docs. Are the docs updated?
Also, does `scripts` also have to be under `html`?

**Comment by edmorley** [comment]
Hi - glad that worked.

The docs say:

```
      // Change options related to generating the HTML document
      // See @neutrinojs/html-template for the defaults
      // used by the Web preset
      html: {},
```

There may be a way to make this clearer - we're open to suggestions :-)

>  Also, does `scripts` also have to be under `html`?

Yeah anything to do with the generated html needs to be under the option named `html`.

**Comment by pdoongarwal** [comment]
I guess a mention in [html-template usage](https://neutrinojs.org/packages/html-template/#usage) section as other variables are mentioned could help. Somewhat, the way html-webpack guys have done [here](https://github.com/jaketrent/html-webpack-template#example).
