### ISSUE TITLE
Configure CSS sourcemaps when sourcemaps are enabled

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1140]
Currently `@neutrinojs/style-loader` doesn't set `sourceMap: true` anywhere:
https://github.com/neutrinojs/neutrino/blob/master/packages/style-loader/index.js

It seems like we should perhaps be doing so when JS source maps are enabled?
https://github.com/webpack-contrib/style-loader#options
https://github.com/webpack-contrib/css-loader#sourcemap
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/aa993daa12a45a326abcdd4f19dcba76db35ed8a/src/index.js#L29

One caveat is that the css-loader docs say:

> They are not enabled by default because they expose a runtime overhead and increase in bundle size (JS source maps do not). In addition to that relative paths are buggy and you need to use an absolute public path which include the server URL.

**Comment by eliperelman** [comment]
> you need to use an absolute public path which include the server URL

This part is super annoying, so I don't think we should do this. Thoughts?

**Comment by edmorley** [comment]
Yeah lets punt for now.

**Comment by edmorley** [comment]
It seems like it's no longer necessary to enable source maps separately, so nothing to do here anyway :-)
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/285#issuecomment-568905994
