### ISSUE TITLE
Provide Third-Party Middleware Guidelines

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#1142]
Expanding on some thoughts posted here: https://github.com/neutrinojs/neutrino/issues/1104#issuecomment-424661310

…and from @edmorley in https://github.com/neutrinojs/neutrino/issues/1104#issue-360847315
> I think for Neutrino we need to be aiming for:
>   * the top-level monorepo presets (eg web/react/airbnb/...) to satisfy the ~80% case.
>   * certain very carefully chosen specific features to be available via opt-in monorepo presets, taking into account:
>     * how many projects might use it
>     * ease of us picking defaults that will work for most projects
>     * the complexity of people configuring the feature on their own (ie would it just be a one-liner, or are we saving them time/hassle?)
>   * everything else to be covered by either third-party presets, or else Neutrino API usage in people's own `.neutrinorc.js` -- and for the Neutrino docs to be clear enough to make this easy.

I think its a good call for Neutrino to stick to more common use-cases, and core functionality.

That said, Neutrino could provide guidelines to third-party developers, to make their middlewares "good citizens".

For examples:
- provide some suggestion for naming conventions
- Coding rules, such as "webpack plugins should have a configurable `pluginId`"

This could get us on the way to making a "recommended/vetted" set of third-party plugins.

Related: 

> Also, on the topic of what we include in the monorepo, perhaps it would be useful to have a policy (or at least an informal process) for how we decide whether to include new presets? For example, we could do what the Django project does, and say that first features need to be proven via a third-party package, and once any issues ironed out/a suitable demand seen, only then can it be included in core?

**Comment by edmorley** [comment]
I think for now we can just point people at this issue if the topic comes up. There hasn't been a lot of discussion on this area recently, so it seems less worth the effort of writing docs up for this.
