### ISSUE TITLE
Switch to terser-webpack-plugin

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1146]
We should switch from the webpack 4 default of [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) to [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin) (which will be the default in webpack 5, see webpack/webpack#8036), since the former uses [uglify-es](https://www.npmjs.com/package/uglify-es), which doesn't have the fix for:
terser-js/terser#50

Apparently the perf issue with uglify-es is particularly bad for AngularJS projects, or people using Font Awesome 5 (adding minutes to the build time).

To do this, we'll need to set `config.optimization.minimizer` for the first time, which means we should fix neutrinojs/webpack-chain#95 first.

**Comment by eliperelman** [comment]
https://github.com/neutrinojs/webpack-chain/pull/84

**Comment by edmorley** [comment]
Ah thank you I forgot that was open. Perhaps we should finish it up?

**Comment by eliperelman** [comment]
Agreed, I can take it.
