### ISSUE TITLE
How to add a custom script to Neutrino html middleware?

### ISSUE THREAD

**Issue by THook** [neutrinojs/neutrino#1153]
Hey guys,

I need to add custom script tags to my exported html index file.

Something like:
```
html: {
   title: 'neutrino',
    scripts: [
         '//cdn.mycdn.ly',
         '<script>var myCustomScript = true;</script>'
    ],
 },
```

Is there any way to do this right now?
It seems that `script-ext-html-webpack-plugin` was removed in #470

**Comment by constgen** [comment]
Is it required to be an inline script?

**Comment by THook** [comment]
Not necessarily.

If I'm able do declare an html file that would be injected when webpack bundles my app,
both on dev and production, it would be fine I guess 🙌

**Comment by eliperelman** [comment]
@THook if you are using Neutrino 8, this can be done with the `html.bodyHtmlSnippet` option. In Neutrino 9, currently in beta, you can define your own template and put the snippet in there.

**Comment by THook** [comment]
Thank you @eliperelman that's exactly what I was looking for (but poorly read the docs of https://github.com/jaketrent/html-webpack-template)

**Comment by edmorley** [comment]
Hi!

Another option would be to add `script-ext-html-webpack-plugin` back in your `.neutrinorc.js` using the webpack-chain API.

For example:

```js
// .neutrinorc.js
module.exports = {
  use: [
    ['@neutrinojs/react', {
      // ...
    }],
    (neutrino) => {
      // Note: in Neutrino 8 and earlier the lazy-loading string form is not supported, so this would
      // instead have to be `.use(require('script-ext-html-webpack-plugin')`
      neutrino.config.plugin('copy').use(require.resolve('script-ext-html-webpack-plugin'), [{
        // Options here
      }]);
    },
  ],
};
```

Closing this out since I think it's been answered - but let us know if not :-)

**Comment by katliger-h** [comment]
> @THook if you are using Neutrino 8, this can be done with the `html.bodyHtmlSnippet` option. In Neutrino 9, currently in beta, you can define your own template and put the snippet in there.

@eliperelman Could you please point me to any example of how to define my own template? Cannot find it anywhere in the documentation :( I need to do the same thing as the topic starter: to add a custom script snippet into my Neutrino project.

**Comment by katliger-h** [comment]
Ok, figured it out, I just needed to copy index.ejs from https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs to my project, change it as needed and use template: 'index.ejs' config option.
