### ISSUE TITLE
Linting issue with neutrino v9

### ISSUE THREAD

**Issue by helfi92** [neutrinojs/neutrino#1166]
- What version of Neutrino are you using?
`v9`
- Are you using the Yarn client or the npm client? What version?
yarn, `v1.10.1`
- What version of Node.js are you using?
`v8.10`
- What operating system are you using?
macOS High Sierra
- What did you do?
Attempt to migrate to neutrino v9
- What did you expect to happen?
`yarn start` shows the same linting errors as `yarn lint`
- What actually happened, contrary to your expectations?
`yarn start` shows linting errors but `yarn lint` shows no errors.

Running `yarn start` or `yarn lint` with `console.log(JSON.stringify(neutrino.config.toConfig(), null, 2));` in `.neutrinorc.js` shows the eslint baseConfig extends property set as:

```jsx
  extends: [
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb/index.js",
    "eslint-config-prettier",
    "plugin:react/recommended"
  ],
```

However, when running `eslint --print-config .`, the extends field is set as:

```jsx
  "extends": [
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/best-practices.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/errors.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/node.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/style.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/variables.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/es6.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/imports.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/index.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb-base/rules/strict.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb/rules/react.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb/rules/react-a11y.js",
    "/Users/haali/Documents/Mozilla/projects/taskcluster-web/node_modules/eslint-config-airbnb/index.js",
    "eslint-config-prettier",
    "plugin:react/recommended"
  ]
```

I wonder if there's a merging issue somewhere. Here's the branch where I'm doing the migration: https://github.com/taskcluster/taskcluster-web/pull/157

**Comment by edmorley** [comment]
Hi! Yeah it's possible there is a bug. 

However it's worth noting that:
* `eslint --print-config` resolves the configuration, so I think it's expected that the contents of `extends` appears to be different, due to:
  https://github.com/airbnb/javascript/blob/24da5bb540de12117bcdfa7b6d8ce3c0ff4b6504/packages/eslint-config-airbnb/index.js#L2-L7
  ...ie: the issue might be being caused by something else.
* `yarn lint` defaults NODE_ENV to `production`, whereas `yarn start` defaults it to `development`, so for things like `no-console` (which I see is conditional on `NODE_ENV`), there will be differences (though not applicable in this case given "start" is seeming to be more strict).

What would be useful would be to have the full output of 
* `yarn neutrino --inspect --mode production` (just the eslint section)
* `node -p "require('./.eslintrc.js')"`
* a sampling of the errors reported in `yarn start` but not by `yarn lint`

**Comment by helfi92** [comment]
`yarn neutrino --inspect --mode production`: https://gist.github.com/helfi92/e8e12dd92f12a24ea168056d7ff0fb66
`node -p "require('./.eslintrc.js')"`: https://gist.github.com/helfi92/620ef914c5d3adc976021765477007d1

**Comment by helfi92** [comment]
A sample of errors reported in `yarn start`: https://gist.github.com/helfi92/d40f2da45f34ad4d8b85195fe211fe6c.

**Comment by edmorley** [comment]
I'll take a look soon, just deep in a few other bits at the moment.

> The `env` field is structured a bit differently. Is this expected?

Yeah the schema for `.eslintrc.js` config is different from that accepted by ESLint's API (which is what eslint-loader has to use). See:
https://github.com/eslint/eslint/blob/master/conf/config-schema.js
https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by edmorley** [comment]
> A sample of errors reported in `yarn start`: https://gist.github.com/helfi92/d40f2da45f34ad4d8b85195fe211fe6c.

All of those errors are in `.jsx` files.

The PR's `lint` command uses:
```
$ yarn lint
yarn run v1.12.0
$ eslint --cache --format codeframe --ext mjs,js src test
...
```

ie: `--ext mjs,js` needs to be `--ext mjs,jsx,js`.

See:
https://master.neutrinojs.org/migration-guide/#neutrino-v8-to-v9

> * `neutrino lint` can typically be replaced with `eslint --cache --format codeframe --ext mjs,jsx,js src`.
