### ISSUE TITLE
Several issues with the default @neutrinojs/dev-server configuration

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1169]
Looking deeper into the devServer default configuration (and following on from #1165, #1168 and https://github.com/neutrinojs/neutrino/pull/434#issuecomment-429091460), I've found a few issues and also potential for cleanup in `@neutrinojs/dev-server`:
* the [host](https://webpack.js.org/configuration/dev-server/#devserver-host) setting tries to default to only listening on localhost, however there is a bug in `isLocal()` which means it returns `0.0.0.0` for a `host` that has a port number (eg `localhost:5000`). This means that all `yarn start` invocations are actually publicly exposed by default.
* the [headers](https://webpack.js.org/configuration/dev-server/#devserver-headers-) option is set to `host: publicHost` (eg `host: 'localhost:5000'`), but this option is used for *responses* not *requests*, so it's not clear why that's needed? (ie it's not for proxy requests)
* it sets [public](https://webpack.js.org/configuration/dev-server/#devserver-public), which as far as I can see is only necessary in more advanced workflows (eg proxying requests to webpack-dev-server using nginx), which we can probably remove and let the 1% of people who need it pass the option explicitly
* it sets [publicPath](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-) to `'/'` and [https](https://webpack.js.org/configuration/dev-server/#devserver-https) to `false`, which are unnecessary since they are the default
* the docs section that lists the middleware default options is out of date (eg `stats` and others)

To be honest, I think we should remove most of the custom handling and then just have a few examples in the docs (eg for setting `0.0.0.0` if using from within a docker container). Looking at the git history there have been many regressions due to the complex handling, and I believe it may no longer be required, now that we're using the CLI and not having to:
* patch in the client to the entrypoint:
  https://github.com/neutrinojs/neutrino/pull/852/files#diff-f7eeb689dea27b680d5b7fd733b51ec9L234
* generate the URL for the "open" feature:
  https://github.com/neutrinojs/neutrino/pull/852/files#diff-58db6dba04eacc1bb7d5628fbf89929dL71

...which would have made it hard for someone to configure themselves.

In addition for `@neutrinojs/web` we should:
* see if we can use the empty string for [output.publicPath](https://webpack.js.org/configuration/output/#output-publicpath) instead of `'./'`
* add a comment explaining the need for the `url.resolve()` for [devServer.publicPath](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-)

@eliperelman / @timkelty, thoughts?

**Comment by timkelty** [comment]
👍 for the additions for `@neutrinojs/web`

Everything else you said sounds like the right approach to me at first glance.

**Comment by edmorley** [comment]
Also:
* whilst `@neutrinojs/dev-server` sets `historyApiFallback: true`, it doesn't work out of the box -- filed #1171 for this, since fixing it has bigger implications
* now that we're using webpack-dev-server's CLI, it looks like `devServer.publicPath` inherits from `output.publicPath`, so actually we don't need to be setting both in many cases:
https://github.com/webpack/webpack-dev-server/blob/474022476dc14756f437c1a3f7397f178135453d/bin/webpack-dev-server.js#L142-L152
