### ISSUE TITLE
console.log in neutrino override function would result in the printing of eslintrc config

### ISSUE THREAD

**Issue by jackysee** [neutrinojs/neutrino#1170]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using?
9.0.0-beta.0

- Are you trying to use any presets? If so, which ones, and what versions?
@neutrinojs/airbnb-base 9.0.0-beta.0
@neutrinojs/web 9.0.0-beta.0

- Are you using the Yarn client or the npm client? What version?
npm 6.4.1

- What version of Node.js are you using?
node v10.11.0

- What operating system are you using?
windows

- What did you do?
Doing console.log in neutrino override function, `.neutrinorc.js`
```
module.exports = {
  options: {
    root: __dirname,
  },
  use: [
    '@neutrinojs/airbnb-base',
    [
      '@neutrinojs/web',
      {
        html: {
          title: 'neutrinoV9eslint'
        }
      }
    ],
    neutrino => console.log('here')
  ]
};

```
- What did you expect to happen?
The `.eslintrc.js`, which uses `neutrino().eslintrc()`, should print proper json format.

- What actually happened, contrary to your expectations?
It prints
```
> node -p "require('./.eslintrc.js')"

here
{ root: true,
  plugins: [ 'babel' ],
  parser:
   'C:\\workspace\\web\\neutrinoV9eslint\\node_modules\\babel-eslint\\lib\\index.js',
  parserOptions: { ecmaVersion: 2018, sourceType: 'module' },
  settings: {},
  globals: { process: true },
  rules:
   { 'new-cap': 'off',
     'no-invalid-this': 'off',
     'object-curly-spacing': 'off',
     semi: 'off',
     'no-unused-expressions': 'off',
     'babel/new-cap': [ 'error', [Object] ],
     'babel/no-invalid-this': 'off',
     'babel/object-curly-spacing': [ 'error', 'always' ],
     'babel/semi': [ 'error', 'always' ],
     'babel/no-unused-expressions': [ 'error', [Object] ] },
  env: { es6: true, browser: true, commonjs: true },
  extends:
   [ 'C:\\workspace\\web\\neutrinoV9eslint\\node_modules\\eslint-config-airbnb-base\\index.js' ] }
```
Eslint cannot consume this file.

Example repo: https://github.com/jackysee/neutrinoV9eslint

**Comment by edmorley** [comment]
Do you mean you'd like to be able to copy the object and paste it into a static `.eslintrc.js` file that doesn't call Neutrino's API, but can't due to the `[ 'error', [Object] ]`?

**Comment by jackysee** [comment]
I think the problem is how I generate the the config to let sublimelinter-eslint's use. I will close this now.
