### ISSUE TITLE
Add SSR how-to

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#1177]

**Comment by edmorley** [comment]
Vue's pages for reference:
https://vuejs.org/v2/guide/ssr.html
https://ssr.vuejs.org/

Though reading through those (I've not set up SSR myself before, so served as a starting point) makes me wonder how useful a guide we could create, given that is seems like an SSR implementation is always going to be very framework and project specific.

As mentioned in https://github.com/neutrinojs/neutrino/pull/1175#discussion_r225140500 it also feels like this is something that would be good to have documented in webpack's docs - which we could then link to.

**Comment by timkelty** [comment]
Component rendering SSR (Vue/React) is indeed very platform/app specific, and I think trying to manage our own guide would be tough.

BYO-"traditional"-server-rendering (not sure what else to call it, as SSR typically refers to server-rendering SPAs…) on the other hand is pretty much the same, e.g.:

```js
module.exports = {
  options: {

    // Nest your webpack assets within your web root
    output: 'public/build',
  },
  use: [
    ['@neutrinojs/web', {

      // BYO-HTML
      html: false,

      // Serve everything from `/build/*`
      publicPath: `/${basename(neutrino.options.output)}/`,

      devServer: {
        proxy: {

          // Proxy all requests to your running app
          '**': {
            target: 'http://localhost:3000',

            // Hint to your app if this is a dev-server request or not.
            // If not, parse manifest.json and use hashed assets in your templates.
            headers: {
              'X-Dev-Server-Proxy': process.env.DEV_SERVER_PROXY
            }
          }
        },
      },
    }]
  ]
};
```

**Comment by xyyjk** [comment]
A react ssr demo based on neutrino
https://github.com/xyyjk/react-ssr/tree/hooks

**Comment by dparker2** [comment]
For disabling the html generation, is simply doing
```
...
    html: false,
...
```
the recommended way to do that? Or is it better to remove it from the config like here: https://github.com/neutrinojs/neutrino/issues/168#issuecomment-292237134?

**Comment by timkelty** [comment]
@dparker2 you got it. `html: false` is what you want. That comment pre-dated the option to remove it via `false`
