### ISSUE TITLE
Exclude wasm from babel-loader rule regex

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1179]
The default file extensions list includes `.wasm` (since it's in webpack's default resolve list), however we also set it for `@neutrinojs/compile-loader`, which I don't think is correct since webpack has its own default rule for WASM:

```js
      /* neutrino.config.module.rule('lint') */
      {
        test: /\.(wasm|mjs|jsx|js)$/,
```

I think we should move it from `neutrino.options.extensions` to only `neutrino.config.resolve.extensions` (like we do for `json`).

**Comment by edmorley** [comment]
A few things that need to be figured out:
* should `.wasm` ever be linted with eslint? (I see there is an eslint plugin, but does eslint blow up without it?)
* should `.wasm` ever be transpiled with babel? I'm presuming not, but I can't find a definitive answer.
* if the answer to both of those is "no", then we can move wasm out of `neutrino.options.extensions` like we do for `json` -- however we then have both `wasm` and `json` as hardcoded extensions listed in three presets (web/node/library). I was thinking we could move them to `extensions.js`, however we also need to make sure that `wasm` is prepended to webpack's `resolve.extensions`, whereas `json` should be appended. To support that we'd end up having to add `resolve_prepend: ['wasm']` and `resolve_append: ['json']` constants to `extensions.js`, which may/may not be worse than the duplication, I can't decide.

@eliperelman (or anyone else), thoughts?

Also I spotted the extensions list here still mentions `.vue` / `.ts` etc:
https://github.com/neutrinojs/neutrino/blame/47ae54ce544b256973adf7c97cca09b26ab6d507/docs/creating-presets.md#L297
https://github.com/neutrinojs/neutrino/blame/47ae54ce544b256973adf7c97cca09b26ab6d507/docs/api.md#L181
https://github.com/neutrinojs/neutrino/blame/47ae54ce544b256973adf7c97cca09b26ab6d507/docs/api.md#L306

**Comment by eliperelman** [comment]
My inclination is that the first 2 points are probably not relevant, i.e., no linting nor babel needed.

**Comment by eliperelman** [comment]
I think the duplication here would be OK, providing we add a relevant comment to each noting that a change in one place should be made in all.
