### ISSUE TITLE
Publish new beta

### ISSUE THREAD

**Issue by Graf009** [neutrinojs/neutrino#1186]
Hi, a lot of changes have already accumulated since the release of beta.0, please release a new beta for testing version 9.
Thanks!

**Comment by edmorley** [comment]
Hi! I'm keen to release a new beta very soon. The last two breaking changes we have in the v9 milestone now have PRs open - I'm just waiting for the GitHub incident to end to merge one and retrigger Travis/request review for the other. After that I'd like to release a new beta today/tomorrow.

**Comment by edmorley** [comment]
@eliperelman I don't suppose toda you'd be able to publisha new beta today? The changes since the previous one are:
https://github.com/neutrinojs/neutrino/compare/d48eb35...master

**Comment by eliperelman** [comment]
OK, all the packages should now be published at `9.0.0-beta.1`. I have also re-tagged this version as both `beta` and `next` for all these packages. I have also deprecated `loader-merge` for `9.0.0-beta.0`.

**Comment by edmorley** [comment]
Many thanks :-)
