### ISSUE TITLE
Consider adding a .gitignore during create-project

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1197]
This would save users having to manually ignore `node_modules/` and `build/` themselves, and is what CRA does.

Whilst it does mean us making an assumption about their choice of VCS:
1. git is pretty common
2. if they don't use Git, they can at least convert the `.gitignore` contents to the VCS format they use (and it will remind them to do so), or just delete the file

Note: We'll need to be careful if we decide to include the file in the neutrino package, since `npm pack` renames any found `.gitignore` (so we'll either need to ship as a different name inside create-project and rename during creation, or else create the file from scratch during create-project).

**Comment by rajatsharma** [comment]
Can I pick this?

**Comment by rajatsharma** [comment]
Please review my PR #1237

**Comment by edmorley** [comment]
Fixed in #1340.
