### ISSUE TITLE
Tests should support .test.js files in other directories

### ISSUE THREAD

**Issue by piu130** [neutrinojs/neutrino#1205]
#### What is the goal of the change?
Some developers prefer to have their test files along their src files. So we should remove the restriction of having test files only in `test` folder. We should check all files in `test` folder and files with test-like endings in all folders.
#### What are the pros and cons of the change?
Pros: everyone can decide where to place the test files.
#### How to fix
I think we can remove the `${basename(tests)}` [here](https://github.com/neutrinojs/neutrino/blob/master/packages/jest/src/index.js#L78) and `neutrino.options.tests` [here](https://github.com/neutrinojs/neutrino/blob/master/packages/karma/index.js#L33). Then add `test` folder separately.

**Comment by epikhighs** [comment]
Hi, so is the documentation incorrect (https://neutrinojs.org/customization/#optionstests)?  I tried to set the `tests` property to `src` instead and it doesn't seem to work.

**Comment by piu130** [comment]
@epikhighs The documentation is correct. You can add
```js
(neutrino) => {
  neutrino.options.tests = 'src'
}
```
to your neutrino config and it takes the files inside.

But for me the problem is more, it should take all files in `tests` (or other configured directory) and all tests-like files (.spec.js, .test.js, etc.) from all directories as default.

**Comment by piu130** [comment]
@edmorley looks like jest v9 already uses test files in `src`.

Steps to reproduce:

```bash
npx @neutrinojs/create-project@next testDir
cd testDir
cp test/simple_test.js src/
yarn test
```

```
 PASS  src/simple_test.js
 PASS  test/simple_test.js
```

I can't see why. The regex looks ok.
