### ISSUE TITLE
Can not override options.tests to point to src

### ISSUE THREAD

**Issue by epikhighs** [neutrinojs/neutrino#1209]
### Bug

Please try to answer the following questions:

- What version of Neutrino are you using?
8.3.x
- Are you trying to use any presets? If so, which ones, and what versions?
@neutrinojs/mocha 8.3.x
- Are you using the Yarn client or the npm client? What version?
npm 6.x
- What version of Node.js are you using?
node 8.12.0
- What operating system are you using?
win 10
- What did you do?
override the options.tests to `src` but running `npm test` looks inside the `test` directory

I tried using object and function format and it doesn't seem to work.  To reproduce, simply create a new project using `npx @neutrinojs/create-project` and try to move a `simple.test.js` into `src` with the following `.neutrinorc.js` file.

```
module.exports = (neutrino) => {
  neutrino.options.tests = 'src';
  neutrino.use([
    '@neutrinojs/mocha',
    {
      reporter: 'spec'
    }
  ]);
};

// neither formats seem to work
module.exports = {
  options: {
    tests: 'src',
  },
  use: [
    [
      '@neutrinojs/mocha',
      {
        reporter: 'spec'
      }
    ]
  ]
};

```

**Comment by edmorley** [comment]
Hi! I believe this might be fixed in Neutrino 9, without the need to override `options.tests`. Could you give v9 a try? See #1129 for details :-)

**Comment by epikhighs** [comment]
I just tried w/ neutrino 9.x and mocha tests can't read the `simple_test.js` located in src with or without setting the `options.tests` to point to `src`.
