### ISSUE TITLE
What would I have to do to use Preact wth components?

### ISSUE THREAD

**Issue by bingomanatee** [neutrinojs/neutrino#1224]
What would I have to do to use Preact with Components? You can switch it out for Web Apps but not Components.

**Comment by edmorley** [comment]
At the moment I'd recommend using `@neutrinojs/react-components` and then manually applying the same adjustments as in the fairly short Preact preset, from here:
https://github.com/neutrinojs/neutrino/blob/master/packages/preact/index.js
