### ISSUE TITLE
Feature Request: Custom template support

### ISSUE THREAD

**Issue by dankreft** [neutrinojs/neutrino#1241]
I'm looking for a way to make creation of new projects a snap for developers in my organization. The tool that comes closest to achieving what I'm after (configurable, extensible, composable) is Neutrino, but the one blocker for me is the inability (at least as far as I can tell) to create my own directory structures and default files (i.e. templates). 

In particular, Neutrino creates projects that have a src/ and a test/ directory, but we're using a modular directory approach that closely approximates the one laid out in https://medium.com/@alexmngn/why-react-developers-should-modularize-their-applications-d26d381854c1 ... configuring Neutrino to look in the right places is doable (I've already done it), but given that I'm working with a bunch of developers who are not well-versed in React, it would be tremendously helpful if I can provide a bit of boilerplate to get them pointed in the right direction until they learn the ropes (this'll also help their initial code reviews go more quickly as well).

The only solution that I can see that would allow me to achieve my goals, even with V9, would be to do something like this:

1. `npx @neutrinojs /create-project myproject`
2. `cd myproject`
3. `npm i --save-dev out my-custom-middleware`
4. Add my-custom-middleware to the .neutrinorc.js
5. Run a script in `my-custom-middleware` (?) to remove the test/ directory and populate a src/ directory with the desired files and directories

I'm fine with steps 1-4, but step #5 is a bit of a deal-breaker for me--it just feels hacky and something that would turn into a maintenance nightmare over time.

This would be a whole lot easier if we could do something like this:

`npx @neutrinojs/create-project --project my-custom-project myproject`

Where `my-custom-project` would be the name of an npm package to use instead of one of the defaults located at https://github.com/neutrinojs/neutrino/tree/master/packages/create-project/commands/init/templates

Are there any plans to support such a feature? Or, is there an approach I've not considered which would allow me to achieve my goals?

**Comment by eliperelman** [comment]
One other approach would be to use a different tool to scaffold out a Neutrino project, like yeoman. In fact, create-project uses yeoman internally to scaffold out projects.

**Comment by edmorley** [comment]
I think that this use-case is best handled by something external to Neutrino, since it's not really Neutrino-specific. eg yeoman.
