### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [neutrinojs/neutrino#125]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by eliperelman** [comment]
@amilajack wow this is really cool. I'd like to see a PR for it, but it might have to be a separate middleware, e.g. `neutrino-middleware-eslint-compat`. The reasoning being that right now the browerlist is stored with the Babel configuration:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L65

Is there a way to pass a target configuration to the lint plugin?

**Comment by amilajack** [comment]
Yup! The demo shows that. [Here's](https://github.com/amilajack/eslint-plugin-compat#installation) some documentation for how to configure it

**Comment by eliperelman** [comment]
@amilajack It appears that the only configuration options are via package.json or a separate browserlist file. Is there an alternative method for passing these to the plugin?

**Comment by amilajack** [comment]
@eliperelman you can use the `.eslintrc` config. The idea behind using the `browserslist` config is because it would integrate really nicely with [babel-preset-env](https://github.com/babel/babel-preset-env), and [autoprefixer](https://github.com/postcss/autoprefixer) which all share the `package.json` or `browserslist` file for configuration

**Comment by eliperelman** [comment]
What I would like to avoid is forced boilerplate to achieve this. Right now using an eslintrc config requires boilerplate in order to operate, while linting during the build process can be abstracted through presets and middleware. When overriding the browserlist, I think this is acceptable, but currently the default use case is not handled:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L65

We have a list of default browsers provided to babel-preset-env. This isn't stored in configuration; it's stored in code to shift boilerplate away from the user. If the eslint plugin supported passing in the configuration, I think this would be solved. I could then pull from the existing values:

```js
neutrino.config
  .rule('lint')
  .use('eslint')
    .tap(options => merge(options, {
      plugins: ['compat'],
      rules: {
        'compat/compat': ['error', {
          browserlist: /* insert browser list */
        }]
      }
    });
```

Does that make sense?

**Comment by jaridmargolin** [comment]
I like the idea of having this data accessible for various middleware / libraries. I could see a browser list being useful for automated testing, etc...

@eliperelman - What about? default neutrino vals > package.json browserList > package.json neutrino browserList? You get sane defaults to avoid boilerplate, but for power users, they can customize and expose for multiple tools to hook into.

**Comment by eliperelman** [comment]
So, in the link I posted which is for master, you can provide a custom value for the compile targets via `neutrino.options.compile.targets`. The reason that it is not set a browserlist is that this doesn't carry over to the Node.js preset, which also needs compile targets.

I think it is also fine to set these values in package.json and we can pull from them, or other configuration files, but it still doesn't solve the problem of needing to inject this list for the default values.

**Comment by eliperelman** [comment]
The core issue is: _How can someone use this plugin by only installing a dependency; without the need to touch package.json or create an eslintrc file?_

**Comment by eliperelman** [comment]
@amilajack I was doing some source-diving of your plugin, and I think I misread your comment (https://github.com/mozilla-neutrino/neutrino-dev/issues/125#issuecomment-287772113).

Are you saying we should be able to do something like the following?

```js
neutrino.use(loaderMerge('lint', 'eslint'), {
  settings: {
    targets: neutrino.options.compile.targets
  }
});
```

If that's the case, I think your plugin already works like this, and Neutrino does now too, so I think a PR is in order!

**Comment by eliperelman** [comment]
For context, that `settings.targets` line can be added here:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L121

**Comment by constgen** [comment]
Would it even be a reason to highlight errors in code if `babel-plugin-env` polyfills all necessary APIs. I also would like to have this middleware in some presets but it makes no sense in the `neutrino-preset-web` and all others that inherit from it.

**Comment by amilajack** [comment]
@constgen good point. I'll work on better integration with `babel-preset-env`

**Comment by eliperelman** [comment]
Closed for inactivity. Please reopen when we are ready to make movement on this again. Thanks!
