### ISSUE TITLE
Error with fresh install of react preset

### ISSUE THREAD

**Issue by Oblium** [neutrinojs/neutrino#1259]
### Issue
- What version of Neutrino are you using? 
  - neutrino@8.3.0
- Are you trying to use any presets? If so, which ones, and what versions?
  - @neutrinojs/react@8.3.0
  - @neutrinojs/jest@8.3.0
  - @neutrinojs/airbnb@8.3.0
- Are you using the Yarn client or the npm client? What version?
  - yarn create v1.12.3
- What version of Node.js are you using?
  - v11.3.0
- What operating system are you using?
  - macOS High Sierra 10.13.6 (17G65)
- What did you do?
  - I've freshly installed the neutrino project through the create project
  
![image](https://user-images.githubusercontent.com/3975657/50214480-a75b8180-0380-11e9-9003-33f2a63412be.png)

- What did you expect to happen?
  - Opening browser on http://localhost:5000, it should show the demo page of the react preset.
- What actually happened, contrary to your expectations?
  - It isn't showing any content in page, whilst there are some console errors

![image](https://user-images.githubusercontent.com/3975657/50214634-1507ad80-0381-11e9-98ee-420e71baf626.png)

```
Uncaught Error: React-Hot-Loader: AppContainer should be patched
    at AppContainer.render (react-hot-loader.development.js?280f:1325)
    at finishClassComponent (react-dom.development.js?cada:14301)
    at updateClassComponent (react-dom.development.js?cada:14264)
    at beginWork (react-dom.development.js?cada:15082)
    at performUnitOfWork (react-dom.development.js?cada:17820)
    at workLoop (react-dom.development.js?cada:17860)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:199)
    at invokeGuardedCallback (react-dom.development.js?cada:256)
    at replayUnitOfWork (react-dom.development.js?cada:17107)
render @ react-hot-loader.development.js?280f:1325
finishClassComponent @ react-dom.development.js?cada:14301
updateClassComponent @ react-dom.development.js?cada:14264
beginWork @ react-dom.development.js?cada:15082
performUnitOfWork @ react-dom.development.js?cada:17820
workLoop @ react-dom.development.js?cada:17860
callCallback @ react-dom.development.js?cada:149
invokeGuardedCallbackDev @ react-dom.development.js?cada:199
invokeGuardedCallback @ react-dom.development.js?cada:256
replayUnitOfWork @ react-dom.development.js?cada:17107
renderRoot @ react-dom.development.js?cada:17979
performWorkOnRoot @ react-dom.development.js?cada:18837
performWork @ react-dom.development.js?cada:18749
performSyncWork @ react-dom.development.js?cada:18723
requestWork @ react-dom.development.js?cada:18592
scheduleWork @ react-dom.development.js?cada:18401
scheduleRootUpdate @ react-dom.development.js?cada:19069
updateContainerAtExpirationTime @ react-dom.development.js?cada:19097
updateContainer @ react-dom.development.js?cada:19154
ReactRoot.render @ react-dom.development.js?cada:19416
(anonymous) @ react-dom.development.js?cada:19556
unbatchedUpdates @ react-dom.development.js?cada:18952
legacyRenderSubtreeIntoContainer @ react-dom.development.js?cada:19552
render @ react-dom.development.js?cada:19613
load @ index.jsx?7364:6
(anonymous) @ index.jsx?7364:19
./src/index.jsx @ index.js:2241
__webpack_require__ @ index.js:679
fn @ index.js:89
0 @ index.js:2251
__webpack_require__ @ index.js:679
(anonymous) @ index.js:725
(anonymous) @ index.js:728
react-dom.development.js?cada:15749 The above error occurred in the <AppContainer> component:
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by edmorley** [comment]
Hi! Thank you for filing an issue.

I believe this is because in Neutrino 8 the create-project tool didn't pin to a specific version of `react-hot-loader`, which means the new major version is being pulled in instead of the version that Neutrino 8 is compatible with:
https://github.com/neutrinojs/neutrino/blob/v8.3.0/packages/create-project/commands/init/utils.js#L45

This is fixed in Neutrino 9 - could you give the release candidate of that a go? :-)
See #1129 for how to use it.

**Comment by Oblium** [comment]
It has worked perfectly!

The only issue is that I was forced to use the yarn process to create the project because using npx was throwing an error (is another issue, I know, but the system configuration is the one in this issue - not to duplicate it).

![image](https://user-images.githubusercontent.com/3975657/50222250-011b7600-0398-11e9-8fb2-e9fedf0520fe.png)

**Comment by Oblium** [comment]
I've reported this issue in the main thread of the neutrino@9 release so I'm closing this issue.

Many thanks for the support!
