### ISSUE TITLE
create-project defaults to yarn if present even when run via npx

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1260]
To try and reproduce #1249 locally I was hoping to run create-project using npm rather than yarn.

However running `npx @neutrinojs/create-project somename` always results in yarn being used (if it's installed) rather than npm, for the various commands that are run during project creation (such as package installation and initial lint fix).

We should make create-project use the same package manager as it was run with.

**Comment by eliperelman** [comment]
See also https://github.com/yarnpkg/yarn/issues/5063

**Comment by eliperelman** [comment]
https://github.com/yarnpkg/yarn/pull/7127

**Comment by eliperelman** [comment]
As soon as yarn v1.16.0 is out of RC we can remove the current yarn check and use the presence of an environment variable.

**Comment by eliperelman** [comment]
Yarn has been updated to v1.16.0.
