### ISSUE TITLE
create-project removes the project on errors making debugging harder

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1263]
Currently if create-project encounters an error during one of the `_spawnSync()` invocations it removes the newly created project directory:
https://github.com/neutrinojs/neutrino/blob/fce11b6a22c113b16bc17ef5f46f11d9a4a4e902/packages/create-project/commands/init/index.js#L38

However this made debugging #1261 much harder, since I couldn't quickly run the commands by hand in the created project to (a) see the error message (which is currently hidden during create-project due to #1262), (b) iterate on the options to see what worked.

I think that create-project should either:
a) delete the project directory on errors by default, but leave it behind if using `--debug`
b) not delete the project directory on errors at all

Reasons for (a):
- the failure might have just been for a transient issue (eg network issue), so might succeed on the next attempt, and deleting the project directory entirely means they can try again immediately without getting the "directory already exists" error

Reasons for (b):
- varying cleanup behaviour between `--debug` and not debug might be confusing (though could be mitigated by appropriate log output)
- create-project doesn't clean up the project directory if errors occur outside of `_spawnSync()`, so if errors occur elsewhere it's left behind anyway

Either way we should probably add log output along the lines of "Removing project directory", since the cleanup behaviour caused me confusion for a moment whilst debugging #1249 until I remembered it had been added as part of #1079.

**Comment by edmorley** [comment]
@neutrinojs/core-contributors, thoughts on (a) or (b)?

**Comment by eliperelman** [comment]
I prefer (a) with the log output.
