### ISSUE TITLE
Storybook support missing

### ISSUE THREAD

**Issue by slikts** [neutrinojs/neutrino#1273]
[Storybook](https://github.com/storybooks/storybook) is by far one of the most popular tools used with React and it's unclear how to make it work with Neutrino.js. I've tried to use [neutrino-preset-react-storybook](https://github.com/usertech/neutrino-preset-react-storybook), but it doesn't support Storybook v4, and  couldn't get it to work with v3 either; it would just run the normal dev server. It'd be really nice if Storybook would be a supported tool.

**Comment by eliperelman** [comment]
This should be possible in Neutrino 9.

**Comment by edmorley** [comment]
Closing since this is possible in Neutrino 9, for which there is a release candidate available (hopefully the final release will be out soon, but the RC is stable enough that I recommend people use it instead of Neutrino 8).

**Comment by constgen** [comment]
To combine any Neutrino preset with Storybook you can use https://www.npmjs.com/package/neutrino-preset-storybook-react
