### ISSUE TITLE
Create a library of react components

### ISSUE THREAD

**Issue by lean** [neutrinojs/neutrino#1275]
### issue

- What version of Neutrino are you using?
8.3
- Are you trying to use any presets? If so, which ones, and what versions?
 "@neutrinojs/library": "^8.3.0",
 "@neutrinojs/react": "^8.3.0",
- Are you using the Yarn client or the npm client? What version?
npm 6.4.1
- What version of Node.js are you using?
10.15
- What operating system are you using?
linux
- What did you do?
I created this config for a library of components (.neutrinorc.js):
`module.exports = {
  use: ["@neutrinojs/react", ["@neutrinojs/library", { name: "Lib" }]]
}`

- What did you expect to happen?
export a file with the components imported in my src/index
- What actually happened, contrary to your expectations?
I have this error:
`BabelLoaderError: SyntaxError: Unexpected token `

**Comment by eliperelman** [comment]
@lean have you tried using the react-components preset yet?

https://neutrinojs.org/packages/react-components/

**Comment by lean** [comment]
@eliperelman yes I tried, but how could I get a single file? With react-components preset the build process make one file for each component.
I need a single file because I want to distribute as a library.

**Comment by caiooaugusto** [comment]
> @eliperelman yes I tried, but how could I get a single file? With react-components preset the build process make one file for each component.
> I need a single file because I want to distribute as a library.

Same here, i'm using react-components preset, but a want to generate a single file. 

I also configured output to: 

![screenshot from 2019-01-10 10-01-58](https://user-images.githubusercontent.com/4611524/50967274-ca301000-14be-11e9-8595-19d4f3250275.png)

I'm getting this error when tried to use generated component in another application from especified output folder.

![screenshot from 2019-01-10 10-00-06](https://user-images.githubusercontent.com/4611524/50967190-8806ce80-14be-11e9-9b89-4f0f094fbcd0.png)

**Comment by eliperelman** [comment]
I solved this in the past by separating the component from the main export:

`src/components/index.jsx`

```js
export { default as Component1 } from '../Component1.jsx';
export { default as Component2 } from '../Component2.jsx';
```

Does that option work for you?

**Comment by eliperelman** [comment]
Closing as resolved with solution in previous comment. If this doesn't work, please feel free to reopen. Thank you!
