### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by jefffriesen** [neutrinojs/neutrino#128]
I would like to get this working with Electron. This is a naive attempt: https://github.com/jefffriesen/neutrino-electron-reference/blob/master/package.json#L11
```js
"start-electron": "neutrino build && electron ."
```

The problem is that I'm pointing Electron to the production build. So no source maps and no hot reloading. What I think I need is to point Electron to the output of `neutrino start` somehow. Or configure a special build artifact that has source maps, but then I don't have hot reloading.

Here is how @amilajack and crew did it on [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) with Babel & Webpack:
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L23

Here's another example: https://github.com/jschr/electron-react-redux-boilerplate/blob/master/package.json#L47

Any suggestions?

**Comment by eliperelman** [comment]
I don't know much about Electron development, but looking at the dev webpack configuration led to this (https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.development.js#L142-L148)

```js
target: 'electron-renderer',
devServer: {
  port,
  hot: true,
  inline: false,
  historyApiFallback: true,
  contentBase: path.join(__dirname, 'dist'),
  publicPath,
  setup() {
    if (process.env.START_HOT) {
      spawn('npm', ['run', 'start-hot'], { shell: true, env: process.env, stdio: 'inherit' })
        .on('close', code => process.exit(code))
        .on('error', spawnError => console.error(spawnError));
    }
  }
},
```

It maps back to an npm script, but maybe digging there can reveal something more usable from middleware.

**Comment by jefffriesen** [comment]
Now I think I'm a little more confused with the `target: 'electron-renderer'`. 

Here is the `start-hot` npm script:
```
"start-hot": "cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development"
```
https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L21

**Comment by tj** [comment]
good luck, that stuff is so confusing hahah, I'd love to see it abstracted away in here too but Electron is decent now without webpack, you can use async/await and friends in vanilla JS now

**Comment by eliperelman** [comment]
With the fork middleware in flight in #425, I think this re-opens the possibility of making this a reality.

**Comment by edmorley** [comment]
At this point in time we're struggling to maintain the existing Neutrino presets due to lack of maintainers, so I suspect we wouldn't want to take on any new presets for now. 

As such I'm going to close this out, but please continue to use the 👍 on the issue to register interest, and if anyone creates a third-party preset, feel free to drop a link to it here :-)
