### ISSUE TITLE
Is there a community? Where can I discuss or ask for help?

### ISSUE THREAD

**Issue by jangid** [neutrinojs/neutrino#1283]
I am importing jQuery in index.js using

import 'jquery';

There is no error in build but still I cannot use functions 'jQuery()' or '$()'.

**Comment by timkelty** [comment]
@jangid https://spectrum.chat/neutrino is a good place to ask questions like this!

Your problem isn't really a Neutrino issue, but a Webpack one.
You're relying on jQuery/$ to be a global, but it isn't.

Options:

- `import $ from 'jquery';`
- use [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/#usage-jquery) or [exports-loader](https://webpack.js.org/loaders/exports-loader/) to us jQuery or $ as globals.
