### ISSUE TITLE
Where is help?

### ISSUE THREAD

**Issue by jangid** [neutrinojs/neutrino#1287]
### Where is help?

As suggested in a previous issue, I posted my query in spectrum-chat but it seems no one is active there? May I know where to get help on the project.

**Comment by edmorley** [comment]
Hi! We're not using Spectrum as actively as we were in the past. The links to it have been removed from the Neutrino v9 docs (currently on `master`; https://master.neutrinojs.org), but they are unfortunately still on the Neutrino v8 docs.

I see this question from you:
https://spectrum.chat/neutrino/general/where-to-set-parser-babel~583cbf6f-c01a-4ab1-af7a-d5553931ea04

That type of an issue is more of a bug than a question, so filing an issue on the GitHub tracker is actually best over a Spectrum thread anyway - which you've done in #1288, so I think we're all set here now :-)

Hopefully we'll (finally) get Neutrino v9 out in the next week or two, and so the confusing links to Spectrum will go away.
