### ISSUE TITLE
{parser: babylon} is deprecated 

### ISSUE THREAD

**Issue by jangid** [neutrinojs/neutrino#1288]
### {parser: babylon} is deprecated

I am using latest neutrinojs. I am using airbnb-base, mocha, vue, style-loader presets. And I get this warning when I "yarn start":

`{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.`

**Comment by edmorley** [comment]
Hi! By latest neutrinojs do you mean v8 or the v9 beta?

It looks like that warning comes from `vue-loader`, and has been fixed upstream in the last 24 hours:
vuejs/vue-loader/pull/1480

**Comment by jangid** [comment]
> Hi! By latest neutrinojs do you mean v8 or the v9 beta?

I have 8.3.0 installed via yarnpkg.

**Comment by edmorley** [comment]
Ah thank you. I would switch to the Neutrino v9 beta, which is using vue-loader v15, that is not affected by the upstream change in prettier. For how to try the beta, see #1129 :-)
