### ISSUE TITLE
Import Statement Without Relative Paths

### ISSUE THREAD

**Issue by luke-infersens** [neutrinojs/neutrino#1299]
### Question

Hi,

Thanks for the project - already saved me loads of time setting up a new project :)

May I ask how I might go about setting the `resolve.modules` property as described here...

https://moduscreate.com/blog/es6-es2015-import-no-relative-path-webpack/

I've tried adding the code...

`resolve: {
  modules: [
    path.resolve('./src'),
    path.resolve('./node_modules')
  ]
},`

....to various place within my `.neutrinorc.js` file but no joy.

I'd like my import to be `import MyComponent from 'src/components/MyComponent'`

Many thanks.

**Comment by eliperelman** [comment]
See also #747. Let me know if that doesn't work for you. Thanks!
