### ISSUE TITLE
@neutrinojs/fork (react + node) and jsx notation result in Module build failed: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by leibowitz** [neutrinojs/neutrino#1302]
### Bug or issue?
Not sure

Please try to answer the following questions:

- What version of Neutrino are you using?
8.3.0
- Are you trying to use any presets? If so, which ones, and what versions?
neutrinojs/react 8.3.0
neutrinojs/node 8.3.0
neutrinojs/fork 8.3.0
- Are you using the Yarn client or the npm client? What version?
yarn 1.13.0
- What version of Node.js are you using?
v11.7.0
- What operating system are you using?
Mac OS Mojave (10.14.2)
- What did you do?
Follow the quickstart for the fork preset
https://neutrinojs.org/packages/fork/#quickstart
- What did you expect to happen?
For JSX files to be parsed with JSX notation.
- What actually happened, contrary to your expectations?
.jsx files are loaded, but errors are thrown as soon as a (<Component />) is seen in the code:
> Module build failed: SyntaxError: Unexpected token

### Feature request or enhancement?
No idea

Please describe your request in detail. Use the following questions as guidance: 

- What is the goal of the change?
If the documentation is missing some information to make it work with .jsx notation, please update the documentation.
- What are the pros and cons of the change?
N/A
- Could this dramatically improve the experience of our users?
Yes. As a new user, I would expect this example to work. I've been searching the web for hours for solutions, but cannot make it to work. Most of the solutions I've explored are probably unnecessary (and most likely plain wrong). Examples include using [babel-register](https://medium.com/@remarkablemark/server-side-rendering-with-react-46715f501651)

Could anyone point out what is needed?

**Comment by leibowitz** [comment]
I've noticed two things since posting this:  
- @neutrinojs/fork is deprecated in neutrino 9+
- it looks like what I am trying to do (developing a react app using react-dom and nodejs) wouldn't work with @neutrinojs/fork, as this is only for building two completely separate app (from what I understand)

Therefore, I guess I need to bundle two separate presets, which would require writing a custom preset and that this task is not trivial, right?

**Comment by edmorley** [comment]
Hi!

What does your project do / could you expand on "React+node"? :-)

**Comment by leibowitz** [comment]
Any project doing Server-Side Rendering with react would need this
https://medium.freecodecamp.org/demystifying-reacts-server-side-render-de335d408fe4

**Comment by leibowitz** [comment]
going to close this issue, since it's not really related to @neutrinojs/fork
