### ISSUE TITLE
React single page app support is broken

### ISSUE THREAD

**Issue by davidje13** [neutrinojs/neutrino#1306]
- What version of Neutrino are you using? **8.3.0**
- Are you trying to use any presets? If so, which ones, and what versions? **@neutrinojs/react 8.3.0**
- Are you using the Yarn client or the npm client? What version? **npm 6.5.0**
- What version of Node.js are you using? **11.6.0**
- What operating system are you using? **macOS 10.14.3**

### What did you do?

1. Configure standard react app using `npx @neutrinojs/create-project myProject` with react and nothing else.
2. Disable hot module swapping (`['@neutrinojs/react', {hot: false}]`, and remove code from index.js) due to unrelated bug #1291
3. `npm start`

### What did you expect to happen?

Visiting http://localhost:5000/abc/def should show the same content as http://localhost:5000/abc

(the [documentation](https://neutrinojs.org/packages/react/#advanced-configuration) states: "This means that the Web preset is optimized toward the use case of single-page applications over multi-page applications")

### What actually happened, contrary to your expectations?

Blank page. The main Javascript file is loaded using a relative path, so any path which is not at the root level will fail. This affects the `start` command and the output of the `build` command.

---

Note that `create-react-app` avoids this problem by specifying absolute paths inside the generated `index.html`. It allows manipulation of the base path through an environment variable `PUBLIC_URL`.

**Comment by davidje13** [comment]
I found that specifying `['@neutrinojs/react', {publicPath: '/'}]` makes this work.

Also looks like this has already been fixed in https://github.com/neutrinojs/neutrino/pull/1185, so I guess it will be fixed in 9?

**Comment by eliperelman** [comment]
Yep, that's correct! Hope to get that out soon.
