### ISSUE TITLE
SyntaxError when using @neutrinojs/jest with MJS dependencies 

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1326]
In mozilla/treeherder/pull/4625, Travis is failing with:

```
$ node ./node_modules/jest/bin/jest
 FAIL  tests/ui/unit/react/bugfiler_test.jsx
  ● Test suite failed to run
    /home/travis/build/mozilla/treeherder/node_modules/node-fetch/lib/index.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Stream from 'stream';
                                                                                                    ^^^^^^
    SyntaxError: Unexpected identifier
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/fetch-mock/src/server.js:1:42)
```

This is because [node-fetch](https://github.com/bitinn/node-fetch) v2 has a `.mjs` entrypoint, referenced from `module` in it's `package.json`, and Jest doesn't support ES6 style imports. 

However it does not occur with Jest defaults, only when using `@neutrinojs/jest`.

This is because:
* Neutrino does not configure dependencies to be transpiled using Babel, only the project's first party sources. (Or more specifically, it leaves Jest `transformIgnorePatterns` at the default of `["/node_modules/"]`).
* `@neutrinojs/jest` overrides Jest's default value for [moduleFileExtensions](https://jestjs.io/docs/en/configuration.html#modulefileextensions-array-string) (which is `["js", "json", "jsx", "ts", "tsx", "node"]`) to instead include additional extensions, such as `mjs`.

Until Jest supports ESM, the configuration needs to be changed so that this doesn't occur. It seems that `moduleFileExtensions` is probably the best place to fix this.

@neutrinojs/core-contributors, thoughts?

**Comment by eliperelman** [comment]
I have been reading through the options here and nothing looks all that ideal. Is the proposal just to remove `mjs` from `moduleFileExtensions`?

**Comment by sarah-clements** [comment]
Moving comment to here instead of Ed's pr: When will this patch be released?

**Comment by edmorley** [comment]
It would be good to get another release candidate out soon. I tried to do one the other day but hit an error message, and now quite busy with the new job so haven't had a chance to look again.
