### ISSUE TITLE
Using `useBuiltIns` option without declaring a core-js version

### ISSUE THREAD

**Issue by armenzg** [neutrinojs/neutrino#1367]
I upgraded to Neutrino 9 rc 1 in this PR:
https://github.com/mozilla/bugzilla-dashboard/pull/82

I've been getting the core-js warning that others have reported.

This PR seems to have improved the situation for |yarn start| and |yarn test|:
https://github.com/neutrinojs/neutrino/pull/1341

However, if I run |yarn build| I get the warning:

```
Armens-MacBook-Pro:bugzilla-dashboard armenzg$ yarn build
yarn run v1.15.2
$ webpack --mode production

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```

**Comment by eliperelman** [comment]
https://github.com/neutrinojs/neutrino/pull/1366

**Comment by armenzg** [comment]
Anyway I can test this change locally before the next rc? (unless the rc is somewhat soon)

Thanks for the fix!

**Comment by edmorley** [comment]
Yeah - I would:
1. Update to the latest RC release (RC1)
2. `git clone https://github.com/neutrinojs/neutrino && cd neutrino`
3. `yarn && yarn link:all`
4. `cd <your project>`
5. `yarn link @neutrinojs/web` (which will make it use the version from the repo instead)

**Comment by armenzg** [comment]
That worked. Thank you!
