### ISSUE TITLE
Migration still fails with v9.0

### ISSUE THREAD

**Issue by YahngSungho** [neutrinojs/neutrino#1368]
v9.0.0-rc.1 has been released, which means the docs on master now match the latest pre-release version. The core-js warning still exists (pending #1366), however it shouldn't stop anything working :-)

_Originally posted by @edmorley in https://github.com/neutrinojs/neutrino/issues/1350#issuecomment-484225792_

**Comment by edmorley** [comment]
Let's reopen #1350 instead :-)
