### ISSUE TITLE
@neutrino/library ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Tassfighter** [neutrinojs/neutrino#1382]
regeneratorRuntime.mark(function _callee() {
      ^

ReferenceError: regeneratorRuntime is not defined
    at /mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:211:7
    at /mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:242:6
    at Module../src/server/index.js (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:246:2)
    at __webpack_require__ (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:30:30)
    at Module../src/index.js (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:108:65)
    at __webpack_require__ (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:30:30)
    at Object.0 (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:279:18)
    at __webpack_require__ (/mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:30:30)
    at /mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:94:18
    at /mnt/work/gitlab/platform/mediq/packages/full-stack/node/build/index.js:97:10

Please try to answer the following questions:

- What version of Neutrino are you using? 9.0.0-rc.1
- Are you trying to use any presets? If so, which ones, and what versions?
"@neutrinojs/airbnb-base": "9.0.0-rc.1",
"@neutrinojs/jest": "9.0.0-rc.1",
"@neutrinojs/library": "9.0.0-rc.1",
- Are you using the Yarn client or the npm client? What version? npm, but it seems like yarn is used under the hood by neutrino when creating the project.
- What version of Node.js are you using? 10.15.3
- What operating system are you using? Ubuntu 16.04 LTS
- What did you do? Migration from neutrino 9.0.0-rc.0 to 9.0.0-rc.1
- What did you expect to happen? Node Library should work as in 9.0.0-rc.0
- What actually happened, contrary to your expectations? 
ReferenceError: regeneratorRuntime is not defined

```
// .neutrinorc.js 9.0.0-rc.0
module.exports = {
  options: {
    root: __dirname,
  },
  use: [
    '@neutrinojs/airbnb-base',
    [
      '@neutrinojs/library',
      {
        name: 'full-stack-node',
        target: 'node',
        libraryTarget: 'commonjs2',
      }
    ],
    '@neutrinojs/jest'
  ]
};
```

```
// .neutrinorc.js 9.0.0-rc.1
const airbnbBase = require('@neutrinojs/airbnb-base');
const library = require('@neutrinojs/library');
const jest = require('@neutrinojs/jest');

module.exports = {
  options: {
    root: __dirname,
  },
  use: [
    airbnbBase(),
    library({
      name: 'full-stack-node',
        target: 'node',
        libraryTarget: 'commonjs2',
    }),
    jest(),
  ],
};
```

**Comment by eliperelman** [comment]
Can you share any of the application code? I am wondering what functionality you may be using that may need to be polyfilled. According to the docs for library:

> Important! This preset does not include @babel/polyfill for size reasons. If you need polyfills in your library code, consider importing @babel/polyfill, core-js, or other alternative.

**Comment by Tassfighter** [comment]
This is how I use the library. 

```
import Node from 'full-stack-node';

const routes = [];

const context = {
  port: process.env.PORT || 8200,
};

const server = new Node.Server({ context, routes });

server.start();
```

**Comment by Tassfighter** [comment]
Seems like this is the same error:
[1417](https://github.com/neutrinojs/neutrino/issues/1417)

So the issue is in neutrino's library preset and react-component preset.
Some how they cannot handle async/await.

**Comment by Tassfighter** [comment]
@eliperelman  Thanks! Finally I got it...
```
import "core-js/stable";
import "regenerator-runtime/runtime";
```
from 
[babel-polyfill](https://babeljs.io/docs/en/babel-polyfill)
