### ISSUE TITLE
npx @neutrinojs/create-project@next unsuccessfully.

### ISSUE THREAD

**Issue by Tassfighter** [neutrinojs/neutrino#1388]
> npx @neutrinojs/create-project@next user
> npx: installed 354 in 7.918s
>                         _          _
>     _ __    ___  _   _ | |_  _ __ (_) _ __    ___
>    | '_ \  / _ \| | | || __|| '__|| || '_ \  / _ \
>    | | | ||  __/| |_| || |_ | |   | || | | || (_) |
>    |_| |_| \___| \__,_| \__||_|   |_||_| |_| \___/
>   
> Welcome to Neutrino! 👋
> To help you create your new project, I am going to ask you a few questions.
> 
> ? 🤔  First up, what would you like to create? Components
> ? 🤔  Next, what kind of components would you like to create? React Components
> ? 🤔  Would you like to add a test runner to your project? Jest
> ? 🤔  Would you like to add linting to your project? Airbnb style rules
> 
> 👌  Looks like I have all the info I need. Give me a moment while I create your project!
> 
>    create user/package.json
>    create user/.neutrinorc.js
>    create user/.eslintrc.js
>    create user/webpack.config.js
>    create user/src/index.jsx
>    create user/src/components/Example/index.jsx
>    create user/jest.config.js
>    create user/test/simple_test.js
> 
> ⏳  Installing devDependencies: @neutrinojs/react-components@^9.0.0-rc.3, neutrino@^9.0.0-rc.3, prop-types@^15, react@^16, react-dom@^16, webpack@^4, webpack-cli@^3, webpack-dev-server@^3, @neutrinojs/jest@^9.0.0-rc.3, jest@^24, @neutrinojs/airbnb@^9.0.0-rc.3, eslint@^5
> ⏳  Performing one-time lint
> ✖ The command "yarn lint --fix" exited unsuccessfully.
> ✖ Cleaning up the incomplete project directory.
> ✖ Try again with the --debug flag for more information and to skip cleanup.

Please try to answer the following questions:

- What version of Neutrino are you using? 9.0.0-rc.3
- Are you trying to use any presets? If so, which ones, and what versions? 
-- React Components
-- Jest
-- Airbnb style rules
- Are you using the Yarn client or the npm client? What version? 
-- npx @neutrinojs/create-project@next
-- npm 6.4.1
-- yarn 1.15.2
- What version of Node.js are you using? 10.15.3
- What operating system are you using? Ubuntu 16.04
- What did you do? create new neutrino project
- What actually happened, contrary to your expectations?
-- create project unsuccessfully because of "yarn lint --fix"

create project works without Airbnb style rules:
> ? 🤔  First up, what would you like to create? Components
> ? 🤔  Next, what kind of components would you like to create? React Components
> ? 🤔  Would you like to add a test runner to your project? Jest
> ? 🤔  Would you like to add linting to your project? None

**Comment by edmorley** [comment]
Hi! What does the output show when using `--debug` (mentioned in the error message)?

**Comment by Tassfighter** [comment]
Intresting!

```
⏳  Performing one-time lint
yarn run v1.15.2
$ eslint --cache --format codeframe --ext mjs,jsx,js src test --fix
error: 'react' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src/components/Example/index.jsx:1:1:
> 1 | import React, { useState } from 'react';
    | ^
  2 | 
  3 | // From https://reactjs.org/docs/hooks-state.html
  4 | export default function Example() {


error: 'react' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src/index.jsx:1:1:
> 1 | import React from 'react';
    | ^
  2 | import { render } from 'react-dom';
  3 | import Example from './components/Example';
  4 | 


error: 'react-dom' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at src/index.jsx:2:1:
  1 | import React from 'react';
> 2 | import { render } from 'react-dom';
    | ^
  3 | import Example from './components/Example';
  4 | 
  5 | render(<Example />, document.getElementById('root'));


3 errors found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ The command "yarn lint --fix" exited unsuccessfully.
```

**Comment by Tassfighter** [comment]
without --debug flag: 
npx 

> @neutrinojs/create-project@next user

creates no project

----------------------------------------------------------------------------------
with --debug flag:  
npx 

> @neutrinojs/create-project@next user --debug

project is created anyways.

**Comment by Tassfighter** [comment]
The lint error remains (of course).
My workaround is to turn off the rule `import/no-extraneous-dependencies` in .neutrionrc.js
```
const airbnb = require('@neutrinojs/airbnb');
const reactComponents = require('@neutrinojs/react-components');
const jest = require('@neutrinojs/jest');

module.exports = {
  options: {
    root: __dirname,
  },
  use: [
    airbnb({
      eslint: {
        baseConfig: {
          rules: {
            // solves: 'react' should be listed in the project's dependencies, not devDependencies
            'import/no-extraneous-dependencies': 'off',
          },
        },
      },
    }),
    reactComponents(),
    jest(),
  ],
};
```

**Comment by edmorley** [comment]
Thank you for filing this. It looks to be a regression from #949 in `v9.0.0-rc.1`.

I've opened #1413 to fix, and in the meantime you can use `--debug` to prevent the generated project from being deleted, then manually add `react`, `react-dom` and `prop-types` under `peerDependencies` in the project's `package.json`. You will then need to delete the `.eslintcache` file to ensure ESLint picks up the change (due to caching issues with `eslint-plugin-import`).
