### ISSUE TITLE
how to use patch-package with react

### ISSUE THREAD

**Issue by k2s** [neutrinojs/neutrino#1391]
I need to use https://www.npmjs.com/package/patch-package in my project. It works fir in development (`yarn start`).

Basically on yarn/npm install commands it will modify content in node_modules package.

This doesn't work with `yarn build`. The package under project/node_modules is patched, but the build process is loading modules from elsewhere and is not executing patch-package.

- Is there possibility/hook to execute command on node_modules folder used for building production ? 
- Where is neutrino sourcind the packages from ?

**Comment by eliperelman** [comment]
Since you are using yarn, have you also used the `postinstall-postinstall` package the docs mention?

**Comment by k2s** [comment]
Found out that it works fine. 
I upgraded the library in my main project and it created nested package. I was not patching that nested package. That confused me.

Neutrino handles it correctly and yes, I use `postinstall-postinstall` too.

**Comment by eliperelman** [comment]
Great! Glad you got it working. 👍
