### ISSUE TITLE
Production build leaks absolute path by default

### ISSUE THREAD

**Issue by crimx** [neutrinojs/neutrino#1416]
### Bug or issue?

Issue.

Please try to answer the following questions:

- What version of Neutrino are you using?
  v8.3.0
- Are you trying to use any presets? If so, which ones, and what versions?
  @neutrinojs/react@8.3.0
- Are you using the Yarn client or the npm client? What version?
  Yarn v1.16.0
- What version of Node.js are you using?
  v10.16.0
- What operating system are you using?
  Arch Linux
- What did you do?
  1. Init project with `yarn add --dev neutrino @neutrinojs/react`
  2. add `src/index.js` with `console.log('hello world')`
  3. run `neutrino build --use @neutrinojs/react`
- What did you expect to happen?
  Should not show absolute path in `build/index.[hash].js`.
- What actually happened, contrary to your expectations?
   In `build/index.[hash].js` (masked):
  ```js
  webpackJsonp(["index"],{"./src/index.js":function(){console.log("hello world")},"multi /home/*******/src/index":function(a,b,c){a.exports=c("./src/index.js")}},["multi /home/*******/src/index"]);
  ```
  Formatted:
  ```js
  webpackJsonp(
    ['index'],
    {
      './src/index.js': function() {
        console.log('hello world')
      },
      'multi /home/*******/src/index': function(a, b, c) {
        a.exports = c('./src/index.js')
      }
    },
    ['multi /home/*******/src/index']
  )
  ```

What is the reason that it was designed this way and how to disable the absolute path? I need consistent output when building on different devices.

**Comment by xyyjk** [comment]
@crimx 

hi~

The [named-modules](https://neutrinojs.org/packages/chunk/#plugins)  plugin is enabled in the default configuration (for improved debugging and console output.)

You can disable it in a production environment:

`.neutrinorc.js`

```JavaScript
module.exports = {
  use : [
    ({ config }) => {
      if (process.env.NODE_ENV === 'production') {
        config.plugins.delete('named-modules');
      }
    },
  ],
};
```

**Comment by crimx** [comment]
@xyyjk Thanks for the solution. But it doesn't work. It still generate absolute path and with extra information.

.neutrinorc.js

```
module.exports = {
  use: [
    '@neutrinojs/react',
    ({ config }) => {
        if (process.env.NODE_ENV === 'production') {
          config.plugins.delete('named-modules');
        }
      }
  ]
}
```

output

```
webpackJsonp(
  [0],
  {
    '/home/*****/node_modules/babel-loader/lib/index.js??ref--1-0!/home/*****/src/index.js': function() {
      console.log('hello world')
    },
    'multi /home/*****/src/index': function(a, b, c) {
      a.exports = c(
        '/home/*****/node_modules/babel-loader/lib/index.js??ref--1-0!/home/*****/src/index.js'
      )
    }
  },
  ['multi /home/*****/src/index']
)

```

**Comment by crimx** [comment]
Removing the `name-all` plugin works.
