### ISSUE TITLE
Now that the PWA middleware is deprecated, any recomendations for offline support ?

### ISSUE THREAD

**Issue by max-l** [neutrinojs/neutrino#1430]
It seems from seeing this PR: https://github.com/neutrinojs/neutrino/pull/1330
that the pwa middleware is deprecated. 

It is still however part of the doc:  https://neutrinojs.org/packages/pwa

I'm new to neutrino, what would be the best way to add offline app with neutrino ?

**Comment by eliperelman** [comment]
This was removed from Neutrino 9, but still exists in Neutrino 8 which is the `latest` on npm, and hence why it is still listed on the documentation. You can take a look at the source code of the pwa package and make your own middleware from it as well, it should be very similar.

If this solution does not work for you, please feel free to discuss. Thanks!
