### ISSUE TITLE
Form a renovate group

### ISSUE THREAD

**Issue by djmitche** [neutrinojs/neutrino#1460]
Renovate's logs for TC contain:
```
INFO: Found sourceUrl with multiple branches that should probably be combined into a group
{
  "sourceUrl": "https://github.com/mozilla-neutrino/neutrino-dev",
  "toVersion": "9.0.0-rc.3",
  "branches": {
    "renovate/neutrinojs-karma-9.x": "@neutrinojs/karma",
    "renovate/neutrinojs-library-9.x": "@neutrinojs/library",
    "renovate/neutrino-9.x": "neutrino",
    "renovate/neutrinojs-airbnb-9.x": "@neutrinojs/airbnb",
    "renovate/neutrinojs-copy-9.x": "@neutrinojs/copy",
    "renovate/neutrinojs-react-9.x": "@neutrinojs/react"
  }
}
```

My understanding of renovate is that a "group" would let users of neutrino get a single PR to upgrade all neutrino things, rather than one per npm package.  I suspect this could be easily submitted upstream to renovate.

**Comment by edmorley** [comment]
Hi! I set this up previously - perhaps something is broken on Renovate's side?
https://github.com/renovatebot/presets/blob/ab46073f25d9c08b15ac9a7b14ab20fc5f55f614/packages/renovate-config-monorepo/generate.js#L64

Of note, the log output above still uses the old repo location `mozilla-neutrino/neutrino-dev` not the location it's been for some time.

**Comment by djmitche** [comment]
Oh, I bet that's because we're not on neturino 9 yet.. ok, invalid issue then :)

**Comment by edmorley** [comment]
I've filed https://github.com/renovatebot/renovate/issues/4607
