### ISSUE TITLE
[Help] Serving bundle

### ISSUE THREAD

**Issue by cassiopagnoncelli** [neutrinojs/neutrino#1524]
Just created the first Neutrino app successfully bundled for production. Directory `build` has 4 files:

```
LpForm.css     LpForm.css.map LpForm.js      LpForm.js.map
```

This was designed to be a component to be used in several other projects. So as Neutrino will just render the component under let's say `<div id="root"></div>`.

Alright, *how do I serve it then in production*?

**My first try:**
In the same directory I created an HTML as follows:

```
<html>
<head>
</head>
<body>
  <div id="root"></div>
  <script src="LpForm.js"></script>
  <link href="LpForm.css" />
</body>
</html>
```

No errors, however nothing renders.

I guess it should be super simple or there must be a tool out there for it. Any help is appreciated.

**Comment by edmorley** [comment]
Hi! Your post doesn't explicitly state this, but from the mention of 'component' I'm guessing this is using `@neutrinojs/react-components`? If so, the idea is that the resultant component would be used as a React component in a similar way to the various React libraries that are out there (ie as part of an app, not the whole app itself), and not be in a form that could be used directly via a `<script>` tag.

The create-project template example here shows one way to use the components:
https://github.com/neutrinojs/neutrino/blob/01f2727387591430959ede70020e5ebb29c20fe3/packages/create-project/commands/init/templates/react-components/src/index.jsx

Does that help? :-)

**Comment by cassiopagnoncelli** [comment]
@edmorley 

Right to the point! 

The create-project template seems to be the closest match. It only turns out that `<script>` tag would always be something different due to file hashes and everything whereas ideally it would be only two imports (a bundled js + a bundled css).

Webpack allows customization of naming, however I don't seem to be able to do that (at least in an easy way). Is there any?

**Comment by edmorley** [comment]
So I think there are really two parts to your question:
1) How do I create a re-usable React component that can be consumed by multiple other projects?
2) How should the "multiple other projects" that consume the component from (1) be built?

For (1), you can use `@neutrinojs/react-components` to generate the built library (then publish to NPM/an internal registry/...).

For (2), you can use `@neutrinojs/react` to build a React web project, that happens to import the component from (1) amongst other dependencies. The `@neutrinojs/react` takes care of things like generating the HTML files that reference the hashed filenames etc. (You can of course use something other than `@neutrinojs/react`, like create-react-app, or a written by hand webpack config etc).

I'd recommend first experimenting with `@neutrinojs/react` to see how Neutrino works for a standard React web app, before then incorporating the custom component aspect :-)

**Comment by cassiopagnoncelli** [comment]
@edmorley That's exactly what I did wherein external script loads the resulting page generated from `@neutrinojs/react` (with some hashed JSs and CSSs) via iframe.

Question, is there a way to do it *without* an ugly iframe?

- One way to do it is by building a Webpack project from scratch;
- Another way is to look into the resulting index.html from `@neutrinojs/react` (with all the hashes) and update the external script with the hashed names.

Maybe there is a Neutrinojs param out there to not generate hashed names so the resulting bundles names are always the same.

**Comment by edmorley** [comment]
I'm not quite sure I follow? The output from `@neutrinojs/react` does not need to be used inside an iframe - I would serve the files in the `build` directory like you'd serve any other assets (eg Netlify, nginx, ...).

> Maybe there is a Neutrinojs param out there to not generate hashed names so the resulting bundles names are always the same.

You can certainly do this, though it is unnecessary if you use the generated `index.html`. 

Could explain why a bit more about why you'd prefer not to use the generated `index.html`  directly, and a bit more about the use-case in general?

**Comment by edmorley** [comment]
To make the output not use hashed filenames, override the value of `output.filename` that is set here:
https://github.com/neutrinojs/neutrino/blob/592837b873f91085216f234fa1f96872edeb8232/packages/web/index.js#L222-L224

To do this, use the approach mentioned here:
https://neutrinojs.org/customization/#advanced-configuration-changes

To override that option use eg:

```js
module.exports = {
  use: [
    react(),
    // ...
    (neutrino) => {
      neutrino.config.output.filename('assets/[name].js');
    }
  ]
};
```

Note: The `filename` option comes from webpack itself (most Neutrino options are really exposed webpack options):
https://webpack.js.org/configuration/output/#outputfilename

**Comment by cassiopagnoncelli** [comment]
Simple and lovely. Thanks so much man!

**Comment by edmorley** [comment]
No problem! :-)
