### ISSUE TITLE
Nested React components

### ISSUE THREAD

**Issue by friedjoff** [neutrinojs/neutrino#1526]
Based on Neutrino 9 I'm trying to create a library which provides multiple React components in a nested directory structure. 

For example ...

```
src/components/Foo1/index.jsx
src/components/bar/Foo2/index.jsx
```
... should result in ...
```
build/Foo1.js
build/bar/Foo2.js
```

Right now this seems not possible based on the `@neutrinojs/react-components` preset. This change seems like an important enhancement for larger React component libraries and I don't see any disadvantage.

**Comment by badazz91** [comment]
Are there any developments on this issue? Is there a middleware that supports nested structures already?

**Comment by badazz91** [comment]
hey - @friedjoff, @edmorley any thoughts on the above? is there an easy way to adjust the existing middleware to achieve this?

would be great if there was a standard solution included.

**Comment by edmorley** [comment]
Hi! I no longer use this project and don't have the time to maintain it unfortunately.
