### ISSUE TITLE
Nested .eslintrc.js files not working with compile-loader

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#1528]
Haven't dug in much, but wanted to post and see if anyone else had this problem.

It appears that nested `.eslintrc.js` aren't being used during compile (using @neutrinojs/eslint).

Running eslint via cli, using `neutrino().eslintrc()` in my root `.eslintrc.js` seems to work just fine.

**Comment by edmorley** [comment]
@timkelty Hi! Do you have an example of a nested eslintrc? I'm not sure I quite follow.

There is quite possibly a bug in:
https://github.com/neutrinojs/neutrino/blob/5fa090c7982bdaee2ea238e7c874e49a3958be99/packages/eslint/index.js#L8-L54
