### ISSUE TITLE
neutrino/react: react-🔥-dom patch is not detected. React 16.6+ features may not work.

### ISSUE THREAD

**Issue by empz** [neutrinojs/neutrino#1543]
### Bug or issue?

Please try to answer the following questions:

I've just generated a project using neutrino/react. Here's the generated `package.json`

```json
{
  "name": "neutrino-react",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "start": "webpack-dev-server --mode development --open",
    "build": "webpack --mode production",
    "lint": "eslint --cache --format codeframe --ext mjs,jsx,js src test"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hot-loader": "^4.12.20"
  },
  "devDependencies": {
    "@neutrinojs/jest": "^9.1.0",
    "@neutrinojs/react": "^9.1.0",
    "@neutrinojs/standardjs": "^9.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.2.0",
    "neutrino": "^9.1.0",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
}
```

Running the generated project without any extra modifications shows the following warning in the browser:
`React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.`

**Comment by eparizzi** [comment]
So the solution is to install a matching version of `@hot-loader/react-dom` and then add the following in neutrino config.
```
neutrino.config.resolve.alias.set("react-dom", "@hot-loader/react-dom");
```

While this is an easy change, I think this should be already included in `neutrino/react`. The generated project should not throw any warning.
