### ISSUE TITLE
Neutrino is borked due to upstream ESLint 7.3.0

### ISSUE THREAD

**Issue by lucasff** [neutrinojs/neutrino#1587]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using?
Latest
- Are you trying to use any presets? If so, which ones, and what versions?
Just trying to use `create-project`
- Are you using the Yarn client or the npm client? What version?
Both, latest.
- What version of Node.js are you using?
v12.16.3
- What operating system are you using?
macOS 10.15.5
- What did you do?
Start a new project using `npx @neutrinojs/create-project offers-table --debug`
- What did you expect to happen?
No errors
- What actually happened, contrary to your expectations?
Failure due to linting.

	Configuration for rule "import/no-cycle" is invalid:
	Value null should be integer.

**Comment by edmorley** [comment]
@lucasff Hi! Thank you for filing the issue. Yeah ESLint 7.3.0 introduced a breaking change/regression (eslint/eslint/issues/13427), which was now been fixed in 7.3.1. You'll need to either use 7.0-7.2 or 7.3.1+.
