### ISSUE TITLE
Multiple React Components Folder

### ISSUE THREAD

**Issue by hjwalt** [neutrinojs/neutrino#1596]
### Enhancement

Currently `neutrino.options.components` or `components` in `react-components` preset only allow a string to be supplied and published as component library. I think allowing an array of string would be useful for that configuration.

My use case is that I need to publish from three different reusable folders with three logical groupings, which are:

1. components
2. containers
3. pages

- What is the goal of the change?
To allow setting multiple component source folder

- What are the pros and cons of the change?
pros: multiple source folders allowed with simple configuration

cons: at the moment all the components would still be published into the same folder, which could be confusing unless the component configuration takes a folder map. i.e. :
```
{
    components: '', // Mapping to build/, there could be other ways to do this better
    containers: 'containers', // Mapping to build/containers
    pages: 'pages' // Mapping to build/pages
}
```

- Could this dramatically improve the experience of our users?
I don't know about other use cases but I think the capability of publishing multiple logical grouping of react components could be useful for other uses as well.

p.s. I am a developer too so if neutrino is open, I could develop an initial change implementation to react-components and create a pull.

**Comment by edmorley** [comment]
Hi! Thank you for filing this issue. This does sound like it would be useful. I don't have much spare time for Neutrino development these days, but if you wanted to open a PR I'd be happy to take a look? :-)

**Comment by hjwalt** [comment]
@edmorley thank you for your response, I have created the pull request for this change.
