### ISSUE TITLE
Switch from eslint-loader to eslint-webpack-plugin

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1637]
Recent Travis runs are showing:

```
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
```

It appears that eslint-loader has been deprecated in favour of eslint-webpack-plugin:
https://github.com/webpack-contrib/eslint-loader#warning-deprecated
https://github.com/webpack-contrib/eslint-webpack-plugin

Sounds like we should switch in Neutrino 10.

**Comment by constgen** [comment]
I would assign this to myself with a pleasure. 
Actually it doesn't require upgrading major version as there no actions from consumer side required. Am I right?

**Comment by edmorley** [comment]
Users could be passing custom options into the loader (via `.neutrinorc.js` customisation), and the new plugin supports different options. As such it's unfortunately a breaking change.

**Comment by constgen** [comment]
You convinced me
