### ISSUE TITLE
Prettier breaks Neutrino webpack chain indent style

### ISSUE THREAD

**Issue by constgen** [neutrinojs/neutrino#1661]
The source code that uses webpack-chain is ugly after Prettier auto-formated it. There are no indents
![изображение](https://user-images.githubusercontent.com/673144/110381990-f164d680-8062-11eb-9fe0-f24a28183775.png)
Should we consider to refuse usage of Prettier in the project and replace it with ESLint formatting rules?

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
