### ISSUE TITLE
OTF fonts not supported by font-loader middleware

### ISSUE THREAD

**Issue by aratcliffe** [neutrinojs/neutrino#1662]
I'm importing a library which uses OTF fonts. These cannot be loaded by the font-loader middleware. Could support for this format be added? In the meantime is it possible to configure the middleware to support this format? I couldn't figure out how to do that.

**Comment by constgen** [comment]
Until this issue is fixed, you can use this local workaround

**.neutrinorc.js**

```js
module.exports = {
  use: [
    // ... your presets here
    function(neutrino){
      neutrino.config.module.rule('font').test(/\.(eot|otf|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/)
    }
  ]
}
```

This will modify extensions for font loader

**Comment by aratcliffe** [comment]
Thank you @constgen. That works perfectly!

**Comment by constgen** [comment]
Lets keep it open. We fix it in the core
