### ISSUE TITLE
nodejs build doesn't includes dependencies

### ISSUE THREAD

**Issue by B-R-Bender** [neutrinojs/neutrino#1676]
- What version of Neutrino are you using?

> "neutrino": "^9.5.0",

- Are you trying to use any presets? If so, which ones, and what versions?

> "@neutrinojs/node": "^9.5.0",

- Are you using the Yarn client or the npm client? What version?

> npm

- What version of Node.js are you using?

> v12.19.0

- What operating system are you using?

> Ubuntu 20

I'm experience an issue (or it's my ignorance), so please clarify it for me.

I've create a nodejs app with `create-project`. I've added this dependencies to `package.json`.
`"dependencies": {
    "@pm2/io": "^5.0.0",
    "uuid": "^8.3.2",
    "ws": "^8.2.2"
  }
`
than I've done `npm run build` and I see no external modules build with my code. I wonder is that I've done something wrong or I need to configure it somehow. But in the docs is stated that:

> Vendoring¶
This preset automatically vendors all external dependencies into a separate chunk based on their inclusion in your package.json. No extra work is required to make this work.

So am i missing something?
Thank you!

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
