### ISSUE TITLE
Setting options.output to relative directory above project directory causes clean middleware to not work

### ISSUE THREAD

**Issue by eliperelman** [neutrinojs/neutrino#362]
If you override the `output` directory like so:

```js
module.exports = {
  options: {
    output: '../build'
  },
  use: ['neutrino-preset-react']
};
```

The `clean` middleware/plugin no longer works.

**Comment by eliperelman** [comment]
The fix for this is to pass the `allowExternal: true` option to the clean middleware. We do not want to do this by default as it poses a risk to the user for accidentally deleting unintended directories.

Instead, the fix for this issue will involve adding a new section to the clean middleware docs outlining how to use the option to remove directories outside of the project directory using this option.

**Comment by Aditi574** [comment]
Hi! I would like to work on this.

**Comment by eliperelman** [comment]
@Aditi574 feel free! As mentioned in my previous comment this would be a documentation change in the `docs` directory as well as the README in the clean package:

> Instead, the fix for this issue will involve adding a new section to the clean middleware docs outlining how to use the option to remove directories outside of the project directory using this option.

**Comment by Aditi574** [comment]
@eliperelman please review my PR #723. Thanks!
