### ISSUE TITLE
Consider using Jest instead of Ava

### ISSUE THREAD

**Issue by okonet** [neutrinojs/neutrino#635]
Ava is awesome but I think Jest offers so much more out of the box. Particularly I wanted to write a test for a fix of #632 but this seems not possible without pulling in at least 2 additional dependencies for 1. mocking and stubbing (sinon?) and 2. for hijacking the node `require` in order to mock the Jest APIs. With Jest that would not require any additional dependencies.

Thoughts?

**Comment by eliperelman** [comment]
I am totally open to using whatever improves our testing situation. I think at the time I used AVA because it was fast, and Jest wasn't really a thing I knew could be used outside React. But yeah, I'm totally open to it.

**Comment by eliperelman** [comment]
As an aside, AVA now supports snapshot testing.
