### ISSUE TITLE
Devise and document an official release process

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#639]
Now that Neutrino is more popular/has more moving parts, I think it's a good time to revisit our release/development process, changing/automating/documenting as appropriate.

We've already moved to the `release/8` branch system (where most development occurs on `master` rather than a `next` type branch), which is a good first step. However I think we should consider also:
* making releases multi-step - where:
  - step 1 is generating the code changes (version bumps/changelogs/...) and opening a PR,
  - step 2 is someone else reviewing the PR,
  - step 3 being merging the PR and pushing the packages to NPM.
  - ...this will allow us to catch any bugs in the automated changelog generation, as well as have a reviewer double-check that a breaking change wasn't accidentally included in a minor version bump etc.
* having a policy of releasing beta versions of new major version releases, before the final version
* having manual testing of a new release, before publishing to NPM (eg using `yarn pack`), until we're confident our end to end tests are fixed and working as expected
* perhaps moving the "publish to NPM" step to CI by making Travis publish when a tag is set
* only releasing at most once a week, unless it's an emergency

...plus anything else people can think of?

**Comment by eliperelman** [comment]
cc: @mozilla-neutrino/core-contributors

**Comment by edmorley** [comment]
Things have improved a fair amount since the issue was posted - I'm happy to call this resolved for now.
