### ISSUE TITLE
README hierarchy - Quickstart/installation

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#644]
Seems a bit odd to me that "Quickstart" (added by #610) does not precede "Installation" in package docs (eg https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/web)

Seems to me a more sensible hierarchy would be:

- Features
- Requirements
- Quickstart
    - create-project
    - Manual Installation
    (including yarn/npm steps that are currently under "Installation"
- Project Layout…

**Comment by divyabaid16** [comment]
Can I work on this issue ?

**Comment by eliperelman** [comment]
@divyabaid16 sure thing! Have a look at the [contributing guide](https://neutrino.js.org/contributing/development.html) as well as the [docs layout](https://raw.githubusercontent.com/mozilla-neutrino/neutrino-dev/master/docs/SUMMARY.md).

Feel free to reach out if you have any questions or encounter issues. Thanks!

**Comment by divyabaid16** [comment]
Please review the PR !
