### ISSUE TITLE
"Use individual modules" warning when installing @neutrinojs/image-minify

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#646]
This may be an upstream issue, but it would be good to chase it down or work around it if possible to avoid users thinking there is something wrong with Neutrino.

```
$ yarn add neutrino @neutrinojs/react @neutrinojs/airbnb @neutrinojs/karma
yarn add v1.3.2
...
warning @neutrinojs/react > @neutrinojs/web > @neutrinojs/minify > @neutrinojs/image-minify 
  > imagemin-mozjpeg > mozjpeg > bin-build > download > gulp-decompress 
  > gulp-util@3.0.8: Use individual modules instead of a grab-bag
...
success Saved 1094 new dependencies.
...
├─ @neutrinojs/minify@8.0.14
├─ @neutrinojs/react@8.0.14
...
├─ @neutrinojs/web@8.0.14
...
├─ bin-build@2.2.0
...
├─ download@4.4.3
...
├─ gulp-decompress@1.2.0
...
├─ gulp-util@3.0.8
...
├─ imagemin-mozjpeg@6.0.0
...
├─ mozjpeg@4.1.1
...
```

**Comment by edmorley** [comment]
I've filed kevva/gulp-decompress#12, since that appears to be where the warning needs to be fixed. Though it's kinda depressing how many sub-dependencies are pulled in for imagemin-mozjpeg.

**Comment by edmorley** [comment]
This is now fixed in gulp-decompress 2.0.2:
https://github.com/kevva/gulp-decompress/commit/d3fdff17810f757056503b0f81a8c06f3fa9dc60

However all of the image minification related deps are using an old version of [bin-build](https://github.com/kevva/bin-build), which pulls in an old [download](https://github.com/kevva/download), which... (you get the idea).

**Comment by edmorley** [comment]
Perhaps we should do the rounds of some of the packages Neutrino directly depends on, asking them to activate the [Renovate](http://renovateapp.com/) service on their repo? (And then recursively, once they are up to date)

**Comment by eliperelman** [comment]
Wontfix due to #1105.
