### ISSUE TITLE
Consolidate references to middleware/presets

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#651]
The docs make explicit references to "middleware" and "presets" separately, but they are really are capable of doing all the same things.

I've seen newcomers be confused by this. Even among middleware authors I've seen the same used interchangeably.

It seems like it might make sense to consolidate the two concepts for simplicity's sake. Especially now that the package names don't contain them.

I'd vote for deprecating references to "preset" and call everything an middleware.

Thoughts @mozilla-neutrino/core-contributors?

**Comment by timkelty** [comment]
That said - people can _name_ their community packages whatever they please (neutrino-x, neutrino-preset-x, neutrino-middlware-x), but perhaps we should provide some recommendations?

**Comment by timkelty** [comment]
Perhaps it is just the structure of the docs that needs to change…right now there are:

- Presets
    - Community Presets
- Middleware
    - Community middleware
- Packages
    - … packages that are middleware/presets

Which is a bit confusing because they're _all_ middleware, and there are also _packages_ that aren't listed there (`create-project`) because they aren't middleware.

- Middleware
    - Core
        - …core middleware
    - Community
        - Preset Middleware

**Comment by eliperelman** [comment]
See https://github.com/neutrinojs/neutrino/pull/1115

**Comment by eliperelman** [comment]
This should be fixed by #1115. Please re-open if that's no the case.
