### ISSUE TITLE
`image-minify` plugin breaks json-loader

### ISSUE THREAD

**Issue by constgen** [neutrinojs/neutrino#670]
Here is a [project sample](https://mega.nz/#!KUMH1IpY!6sfZUI9aNncJ5ScZOrR8yec7G9rd2Cw30BUP6VP2x7c). Steps to reproduce a bug.

1. Install dependencies
2. Run `npm run build`
3. CLI throws an error 

```
✖ Building project failed
./src/config.json
Module parse failed: Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
| {
|     "baseUrl": "default"
| }
```

4. Comment `minify` plugin in `.neutrinorc.js`

```
 // use(minify)
```

5. Run `npm run build`
6. Build is successful. You can check this opening `index.html`

**Expected result:** Build should not fail when minification is enabled
**Actual result:** `@neutrinojs/minify` breaks Webpack json-loader

**Comment by eliperelman** [comment]
I can replicate using `@neutrinojs/library` but not `@neutrinojs/react`.
