### ISSUE TITLE
Web preset option to enable sourcemaps in production

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#676]
Currently the Neutrino web preset only enables sourcemaps (specifically `cheap-module-eval-source-map`) in development:
https://github.com/mozilla-neutrino/neutrino-dev/blob/e52919b5ebcd694857bb7a5244afe07ca1299fd1/packages/web/index.js#L187

I imagine some people wouldn't want sourcemaps in production (eg non-open-source), however perhaps it would be worth having an option to enable for those who do? (Which would save users having to figure out which sourcemap type is best for production by reading through all of https://webpack.js.org/configuration/devtool/)

**Comment by edmorley** [comment]
So create-react-app takes the approach of generating source maps by default in production too, and then telling the user to handle them as desired during app deployment (eg restricting access via the server config or just removing them) or else they can set an option to disable:
https://github.com/facebook/create-react-app/blob/bf3d73c2c6fd78d4eea23f5356fb26f3232fabee/packages/react-scripts/config/webpack.config.prod.js#L123-L125

Should we should do this too?

**Comment by edmorley** [comment]
Questions:
1. Should we enable sourcemaps by default in production? (I can't decide; does slow the build down considerably, since the `source-map` devtool type isn't cacheable)
2. Regardless of (1), should we provide an option so people don't have to use the manual API? (I think yes)
3. If we provide an option, should it be "on/off" (with us picking what we feel is the most suitable devtool type and the user having to use the manual API otherwise), or should we allow/make the user pick which type?

To give some alternatives as to how the options could be presented to the user:

Option A...
```js
module.exports = {
  use: [
    [
      '@neutrinojs/react',
      {
        // Always enable sourcemaps, rather than the default of only in development
        // (Neutrino picks the most appropriate source-map for each mode)
        sourcemaps: true,
      }
    ]
  ]
};
```

Option B...
```js
module.exports = {
  use: [
    [
      '@neutrinojs/react',
      {
        sourcemaps: {
          // Override Neutrino's default development sourcemap of 'cheap-module-source-map'
          development: 'eval',
          // Enable sourcemaps in production too.
          // Neutrino will use 'source-map' since not overridden.
          production: true
        }
      }
    ]
  ]
};
```

**Comment by edmorley** [comment]
Meant to say before, for Treeherder, enabling `devtool: 'source-map'` in the prod build increases the warm cache build time from ~15s to 30s.

**Comment by eliperelman** [comment]
If we do enable source-maps by default in production, we should make a note about potential security risks of outputting those source maps publically.

**Comment by edmorley** [comment]
Agreed. Though interestingly, CRA's only mention from that point of view (given they enable by default), is this code comment:
https://github.com/facebook/create-react-app/blob/581c453610f08ef67ed467029ec289cfebe52063/packages/react-scripts/config/webpack.config.prod.js#L97

And the `GENERATE_SOURCEMAP` option here (which only mentions disabling to prevent OOM, rather than any other reason):
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration

**Comment by eliperelman** [comment]
This is blocked by #972.

**Comment by edmorley** [comment]
There are still design decisions here to be made - which are the real blocker IMO.

I think perhaps we should still leave sourcemaps off in production (if only so the out of the box speed is competitive), but it would be good to add an easy option to enable them (and at the opinionated optimal setting).

**Comment by edmorley** [comment]
I propose we:
* continue to default to `cheap-module-eval-source-map` in development (reviewing the differences it seems like the right choice)
* continue to default to no sourcemaps in production (for out of the box speed/privacy)
* call the new preset option `devtool` for consistency with webpack

Still to decide:
* whether sourcemaps should be enabled during testing
  --> I think they perhaps should, given Jest etc support using them for making assertions more useful
  --> should they use `cheap-module-eval-source-map` too / just inherit what's set for development?
* how the new `devtools` option should be structured - which depends on how much configurability we want to allow before users are expected to fall back to the Neutrino config API instead?
