### ISSUE TITLE
'yarn version' fails with 'TypeError: Invalid Version: vundefined'

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#762]
Running `yarn run version` on master (which is run by `yarn release*`; note is not the same as `yarn version`) fails with:

```
yarn run v1.5.1
$ yarn changelog --package && git add CHANGELOG.md
$ auto-changelog --remote upstream --commit-limit false --package
TypeError: Invalid Version: vundefined
    at new SemVer (C:\Users\Ed\src\neutrino-dev\node_modules\semver\semver.js:305:11)
    at compare (C:\Users\Ed\src\neutrino-dev\node_modules\semver\semver.js:578:39)
    at eq (C:\Users\Ed\src\neutrino-dev\node_modules\semver\semver.js:617:10)
    at Function.diff (C:\Users\Ed\src\neutrino-dev\node_modules\semver\semver.js:512:7)
    at parseReleases (C:\Users\Ed\src\neutrino-dev\node_modules\auto-changelog\lib\releases.js:37:66)
    at _callee$ (C:\Users\Ed\src\neutrino-dev\node_modules\auto-changelog\lib\run.js:110:52)
    at tryCatch (C:\Users\Ed\src\neutrino-dev\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Ed\src\neutrino-dev\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Ed\src\neutrino-dev\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Ed\src\neutrino-dev\node_modules\auto-changelog\lib\run.js:31:191)
```

I believe this is because auto-changelog's `--package` option only looks in the monorepo root's `package.json`, and not the individual packages or `lerna.json`.

The fix should be as simple as re-adding the version to the root `package.json` (was previously removed before we used auto-changelog).

**Comment by edmorley** [comment]
So unfortunately the fix of adding a version field to the repo root `package.json` isn't viable, since lerna (apparently by design for `private: true` packages) doesn't increment the version there, meaning it goes out of date.

As such the options seem to be:
1. ask lerna to add an option to bump the root `package.json` regardless
2. ask lerna to set an environment variable that contains the chosen new version number when running publish, so that we can make the `version` lifecycle script be something like `yarn changelog --latest-version $LERNA_PUBLISH_VERSION && git add CHANGELOG.md`
3. ask auto-changelog to make the `--package` mode detect a yarn workspaces repository, and scan all workspace packages looking for the maximum version number 
4. write a version bump script ourselves, that is run via the `version` lifecycle script entry, which extracts the new version number from `lerna.json` and passes that to auto-changelog's `--latest-version X.Y.Z`

@eliperelman, thoughts? I think the best solution would be (1) or (2).

For now the workaround is to just temporarily add the new version number to `package.json` before running `yarn release*`, and then remove it after.

**Comment by eliperelman** [comment]
While those might be the best solutions, I imagine running into a bit of friction either moving forward with it, or not having traction soon enough.

(4) seems simple enough, but I'm not sure lerna actually runs version/preversion.

<sup>Aside: I thought I had mentioned this prior, but I always run the release chain with npm instead of yarn because of credential issues.</sup>

**Comment by edmorley** [comment]
lerna publish does run `version`, hence getting the error above (without it, the changelog wouldn't be automatically updated). Yeah I remember you saying about npm for credentials, but they work fine for me with yarn once already logged in. The error above affects both npm and yarn.

Anyway I used the workaround mentioned above to be able to get 8.2.0 published for now.

**Comment by eliperelman** [comment]
@edmorley I think this may now be fixed by the Lerna 3 commit, do you agree?

**Comment by edmorley** [comment]
Yeah :-)

**Comment by edmorley** [comment]
This is still broken for me, sigh.
