### ISSUE TITLE
Nuxt.js Middleware and/or examples

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#771]
Nuxt comes with its own server etc, but if you were using it with Neutrino, I'm assuming you'd want to use it as a middleware: https://github.com/nuxt/nuxt.js#using-nuxtjs-as-a-middleware

Hoping I can enlist @kswedberg for help :)

**Comment by edmorley** [comment]
From a quick glance at the Nuxt site/docs it seems like it's something people would use instead of Neutrino, rather than something that should be wrapped inside a Neutrino layer of abstraction. Do you have specific use-cases in mind where it would be useful to use Nuxt with Neutrino?

**Comment by timkelty** [comment]
@edmorley that's correct, it really is it's own ecosystem, with CLI tools, routing, and webpack/build all intertwined, so I think this would be much more than a "simple" middleware. Similar, I think, to making a Neutrino-version of CRA (#556).

TBH, this was a while ago and I was looking over a coworker's shoulder (@kswedberg), but I remember liking parts of it, but the webpack/build portion seemed like a mess. I think I was looking for a way to leverage Neutrino for that, while leveraging Nuxt.js's configuration of server-side component rendering and routing scheme.

**Comment by edmorley** [comment]
Closing this out for now since there haven't been any other requests for Nuxt.js support (I'm guessing since it has it's own server etc). If anyone else would like to see this please do +1 this issue and/or comment.
