### ISSUE TITLE
Vue: CSS extraction/modules support with single-file components

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#776]
Run into this with `@neutrinojs/vue`, though it might be true for react as well…

`<style>` tags in a `.vue` component appear to _not_ be extracted to .css files.

Should they be, or is this expected?

If I want my css extracted, I need to instead `import` in (from component's `<script>` block), and toggle module support with the file name (*.module.css, etc).

Adding the `module` attr does appear to process the styles as css modules, as stated here: https://vue-loader.vuejs.org/en/features/css-modules.html

**Comment by eliperelman** [comment]
Is this still the case with mini-css-extract-plugin in master?

**Comment by timkelty** [comment]
@eliperelman I just tried this with master and I did indeed get a build css file. 🎉
