### ISSUE TITLE
Add more test coverage of non-default middleware

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#837]
Some of the Neutrino middleware isn't used by any of the top level presets, and instead are meant as optional extras. For example ~`@neutrinojs/pwa`~, ~`@neutrinojs/stylelint`~, ~`@neutrinojs/image-minify`~, `@neutrinojs/copy` and ~`@neutrinojs/fork`~.

Whilst some of these have basic tests - they typically only check that the generated `.toConfig()` validates, and not that the build would actually succeed. The latter is covered by the create-project end to end tests for the top level presets, however we'll have to do something else for middleware that create-project doesn't know anything about.

This would help catch issues like:
https://github.com/mozilla-neutrino/neutrino-dev/pull/824#issuecomment-384942483

**Comment by eliperelman** [comment]
As an update here, `@neutrinojs/stylelint`, `@neutrinojs/image-minify`, and `@neutrinojs/fork` have since been removed.

**Comment by edmorley** [comment]
After the recent removals, the only middleware that is not tested via the E2E create-project tests is `@neutrinojs/copy`, which is straight-forwards enough that I think additional testing (beyond its unit test) is unnecessary.
