### ISSUE TITLE
Jest preset improvements

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#851]
Whilst working on #845 I found a few areas of improvement for the Jest preset:
1. it currently both duplicates parts of [babel-jest](https://github.com/facebook/jest/blob/master/packages/babel-jest/src/index.js) but is also missing some of the extra functionality that it offers - so it seems preferable to re-use babel-jest instead
2. ~the Jest config is unnecessarily saved to a temporary file, when we can instead pass via the `config` option (so long as it's stringified to avoid facebook/jest#5429)~ Fixed by #852.
3. the preset sets the `retainLines` option which is no longer necessary, now that jest supports sourcemaps

For (1), see possible alternatives here:
https://github.com/mozilla-neutrino/neutrino-dev/pull/845#discussion_r186408308

**Comment by eliperelman** [comment]
Any updates here? Does this still need to happen as part of v9?

**Comment by SimenB** [comment]
The PR to Jest was released in 23.4.2, I don't think this needs anything from Jest now?

**Comment by eliperelman** [comment]
@edmorley do you think it's sufficient then to just open a patch for the `retainLines` part for v9?

**Comment by edmorley** [comment]
I've opened #1183 which switches us to using babel-jest.
