### ISSUE TITLE
webpack-dev-server missing from react-components project on master

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#962]
Using create-project to create a react-components project, then using `yarn start`, I get:
```
yarn run v1.7.0
$ webpack-dev-server --mode development
'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

We should either add webpack-dev-server to the `devDependencies` matrix in create-project, or else not define the `start` script entry for react-component projects' `package.json`.

Also, if I manually install `webpack-dev-server`, I then get a bunch of `import/no-extraneous-dependencies` errors relating to deps being in `devDependencies` rather than `dependencies`.

**Comment by edmorley** [comment]
@eliperelman, should `@neutrinojs/react-components` be configuring webpack-dev-server?

**Comment by eliperelman** [comment]
@edmorley it used to because `yarn start` would bring in React and start up a little UI, but I think I removed that, but didn't update start. Let me verify that it is in fact gone.

**Comment by eliperelman** [comment]
Hmm no, it's still there lol.

**Comment by eliperelman** [comment]
> Also, if I manually install `webpack-dev-server`, I then get a bunch of `import/no-extraneous-dependencies` errors relating to deps being in `devDependencies` rather than `dependencies`.

The airbnb eslint is annoying in this regard since we don't want React and friends in dependencies when writing components, rather just for apps.

**Comment by eliperelman** [comment]
I've tried solving this a number of ways, but am unhappy with all of them. At this point, I'm tempted to say the solution to this is documentation: we make strong note in the docs that coupling this with the eslint import plugin should have a rule override to account for the devDependencies mismatch.

Thoughts @edmorley?

**Comment by edmorley** [comment]
Works for me :-)

**Comment by eliperelman** [comment]
Going to wait on this one until after the documentation changes have landed.
