### ISSUE TITLE
@neutrinojs/library: the externals options is ignored

### ISSUE THREAD

**Issue by cairomax** [neutrinojs/neutrino#987]
The `externals` options is documented here:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/library/README.md#preset-options

but it appears to me that it is completely ignored by the implementation.
See in particular this line (current master branch):

https://github.com/mozilla-neutrino/neutrino-dev/blob/46b88910a621a4e23b36ae55412b4094504770cc/packages/library/index.js#L74

where `nodeExternals` is invoked without forwarding any options.

**Comment by eliperelman** [comment]
@cairomax would you be interested in submitting a PR to fix that?

**Comment by sloria** [comment]
Ran into this issue and sent a PR (#999)
